import { useState } from 'react';

type Lead = { id: string; name: string; form_name: string; lead_type: string; property_type: string; location: string; budget: string; timeline: string; requirement: string; message: string };
type Property = { id: string; title: string; propertyType: string; location: string; price: string; area: string; status: string };
type Mode = 'analyze' | 'campaign' | 'followup';
type Stage = 'idle' | 'checking' | 'loading' | 'ai';

async function readJson(response: Response) { const raw = await response.text(); try { return raw ? JSON.parse(raw) : {}; } catch { return { error: raw || `HTTP ${response.status}` }; } }
const buttonClass = 'relative z-[100] pointer-events-auto cursor-pointer touch-manipulation select-none active:scale-[0.99] transition-transform';

export default function AiLeadAssistant() {
  const [password, setPassword] = useState(''); const [loggedIn, setLoggedIn] = useState(false); const [mode, setMode] = useState<Mode>('analyze');
  const [text, setText] = useState(''); const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [stage, setStage] = useState<Stage>('idle');
  async function checkPassword() { const enteredPassword = password.trim(); if (!enteredPassword) { setError('Please enter the dashboard password.'); return; } setLoading(true); setStage('checking'); setError(''); try { const r = await fetch('/api/auth',{method:'GET',headers:{Authorization:`Bearer ${enteredPassword}`,Accept:'application/json'},cache:'no-store'}); const x=await readJson(r); if(!r.ok) throw new Error(x.error||`Password check failed (HTTP ${r.status})`); setLoggedIn(true); sessionStorage.setItem('anjanay-heights-crm-password',enteredPassword); } catch(e){setError(e instanceof Error?e.message:'Unable to verify dashboard password.')} finally{setLoading(false);setStage('idle')} }
  async function runAssistant(selectedMode: Mode = mode, userQuestion = '') { if(loading)return; setMode(selectedMode); setLoading(true);setStage('loading');setError('');setText(''); try { const headers={Authorization:`Bearer ${password}`,Accept:'application/json'}; const [lr,pr,mr]=await Promise.all([fetch('/api/leads',{headers,cache:'no-store'}),fetch('/api/properties',{headers,cache:'no-store'}),fetch('/api/lead-meta',{headers,cache:'no-store'})]); const ld=await readJson(lr),pd=await readJson(pr),md=await readJson(mr); if(!lr.ok)throw new Error(`CRM leads API failed: ${ld.error||`HTTP ${lr.status}`}`);if(!pr.ok)throw new Error(`Property API failed: ${pd.error||`HTTP ${pr.status}`}`);if(!mr.ok)throw new Error(`Lead metadata API failed: ${md.error||`HTTP ${mr.status}`}`); const leads=(ld.leads||[]).map((l:Lead)=>({...l,...(md.meta?.[l.id]||{})})); const properties=(pd.properties||[]).map((p:Property)=>({id:p.id,title:p.title,propertyType:p.propertyType,location:p.location,price:p.price,area:p.area,status:p.status})); setStage('ai'); const r=await fetch('/api/ai-lead-assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`,Accept:'application/json'},body:JSON.stringify({mode:selectedMode,question:userQuestion,leads,properties}),cache:'no-store'}); const x=await readJson(r); if(!r.ok)throw new Error(`AI API failed: ${x.error||`HTTP ${r.status}`}`); setText(x.text||'No AI response generated.'); }catch(e){setError(e instanceof Error?e.message:'Something went wrong while running AI.')}finally{setLoading(false);setStage('idle')} }
  if(!loggedIn)return <div className="relative z-0 isolate min-h-screen bg-[#F5F7FA] flex items-center justify-center px-4"><form onSubmit={e=>{e.preventDefault();void checkPassword()}} className="relative z-10 w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><div className="text-center"><div className="text-4xl">🤖</div><h1 className="text-3xl font-bold text-[#1A365D] mt-2">AI Sales Assistant</h1><p className="text-gray-500 mt-2">Your CRM-connected sales manager for Anjanay Heights</p></div><label className="block mt-8 mb-2 font-semibold">Dashboard Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" className="relative z-[100] w-full border rounded-xl px-4 py-3 pointer-events-auto" autoComplete="current-password" />{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button type="submit" disabled={loading} className={`${buttonClass} w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold disabled:opacity-60`}>{loading?'Verifying...':'Open AI Assistant'}</button></form></div>;
  const statusText=stage==='loading'?'Loading CRM data...':stage==='ai'?'AI is analyzing your CRM...':'';
  return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-8"><div className="max-w-6xl mx-auto"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6"><div><button type="button" onClick={()=>{window.location.href='/admin'}} className={`${buttonClass} text-sm text-[#1A365D] font-semibold mb-2`}>← CRM Dashboard</button><h1 className="text-3xl font-bold text-[#1A365D]">🤖 AI Sales Assistant</h1><p className="text-gray-500 mt-1">Ask questions and get sales decisions from your live CRM data.</p></div><button type="button" onClick={()=>{setLoggedIn(false);setPassword('');setText('');setError('')}} className={`${buttonClass} bg-white border px-4 py-2 rounded-xl font-semibold`}>Logout</button></div>
  <div className="relative z-10 bg-white rounded-2xl shadow p-5 mb-5"><p className="font-bold text-lg text-[#1A365D]">💬 Ask your AI Sales Manager</p><p className="text-sm text-gray-500 mt-1">Examples: “Which lead should I call first?”, “Who is closest to closing?”, “What properties should I offer Vinay?”</p><form onSubmit={e=>{e.preventDefault();if(question.trim())void runAssistant(mode,question.trim())}} className="flex flex-col md:flex-row gap-3 mt-4"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about my leads, properties or sales..." className="flex-1 border rounded-xl px-4 py-3" /><button disabled={loading||!question.trim()} className={`${buttonClass} bg-[#1A365D] text-white px-6 py-3 rounded-xl font-semibold disabled:opacity-60`}>{loading?'Thinking...':'Ask AI'}</button></form></div>
  <div className="grid md:grid-cols-3 gap-3 mb-5"><button type="button" onClick={()=>void runAssistant('analyze')} className={`${buttonClass} text-left rounded-2xl p-5 border-2 ${mode==='analyze'?'border-[#1A365D] bg-white':'border-transparent bg-white'}`}><div className="text-2xl">🎯</div><p className="font-bold mt-2">Analyze Leads</p><p className="text-sm text-gray-500 mt-1">Top opportunities and today's priorities.</p></button><button type="button" onClick={()=>void runAssistant('campaign')} className={`${buttonClass} text-left rounded-2xl p-5 border-2 ${mode==='campaign'?'border-[#1A365D] bg-white':'border-transparent bg-white'}`}><div className="text-2xl">📣</div><p className="font-bold mt-2">Get More Leads</p><p className="text-sm text-gray-500 mt-1">7-day WhatsApp, Meta and Google plan.</p></button><button type="button" onClick={()=>void runAssistant('followup')} className={`${buttonClass} text-left rounded-2xl p-5 border-2 ${mode==='followup'?'border-[#1A365D] bg-white':'border-transparent bg-white'}`}><div className="text-2xl">💬</div><p className="font-bold mt-2">Follow-up Messages</p><p className="text-sm text-gray-500 mt-1">Ready-to-send WhatsApp follow-ups.</p></button></div>
  {statusText&&<p className="text-sm text-blue-700 mb-3 font-medium">{statusText}</p>}{error&&<div className="bg-red-50 text-red-700 rounded-xl p-3 text-sm mb-4 break-words">{error}</div>}{text?<div className="relative z-10 bg-white rounded-2xl shadow p-6"><h2 className="font-bold text-[#1A365D] text-xl mb-4">AI Recommendation</h2><div className="whitespace-pre-wrap leading-7 text-gray-800">{text}</div></div>:<div className="relative z-10 bg-white rounded-2xl border border-dashed p-10 text-center text-gray-500">Ask a question above or choose an AI sales action.</div>}</div></div>;
}
