import { useMemo, useState } from 'react';

type Lead = { id: string; created_at: string; name: string; phone: string; form_name: string; lead_type: string; source?: string; utm_source?: string; utm_medium?: string; utm_campaign?: string; };

function sourceOf(lead: Lead) {
  const raw = String(lead.source || lead.utm_source || lead.utm_medium || `${lead.form_name || ''} ${lead.lead_type || ''}`).toLowerCase();
  if (raw.includes('whatsapp') || raw === 'wa') return 'WhatsApp';
  if (raw.includes('facebook') || raw.includes('instagram') || raw.includes('meta')) return 'Meta';
  if (raw.includes('google')) return 'Google';
  if (raw.includes('referral') || raw.includes('refer')) return 'Referral';
  if (raw.includes('99acres')) return '99acres';
  if (raw.includes('magicbricks')) return 'MagicBricks';
  return 'Website';
}

export default function CampaignPerformance() {
  const [password, setPassword] = useState('');
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loggedIn, setLoggedIn] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function load() {
    setLoading(true); setError('');
    try {
      const r = await fetch('/api/leads', { headers: { Authorization: `Bearer ${password}` } });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error || 'Unable to load leads');
      setLeads(data.leads || []); setLoggedIn(true);
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load leads'); }
    finally { setLoading(false); }
  }

  const campaigns = useMemo(() => {
    const map = new Map<string, { campaign: string; source: string; medium: string; count: number; latest: string }>();
    for (const lead of leads) {
      const campaign = String(lead.utm_campaign || '').trim() || 'Unattributed';
      const source = sourceOf(lead);
      const medium = String(lead.utm_medium || '').trim() || '—';
      const key = `${campaign}|${source}|${medium}`;
      const existing = map.get(key);
      if (existing) { existing.count += 1; if (lead.created_at > existing.latest) existing.latest = lead.created_at; }
      else map.set(key, { campaign, source, medium, count: 1, latest: lead.created_at });
    }
    return [...map.values()].sort((a, b) => b.count - a.count || b.latest.localeCompare(a.latest));
  }, [leads]);

  if (!loggedIn) return <div className="min-h-screen bg-slate-50 flex items-center justify-center px-4"><form onSubmit={e => { e.preventDefault(); void load(); }} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><h1 className="text-3xl font-bold text-[#1A365D] text-center">Campaign Performance</h1><p className="text-gray-500 text-center mt-2">See which tagged campaigns are generating enquiries.</p><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Dashboard password" className="w-full border rounded-xl px-4 py-3 mt-8" />{error && <p className="text-red-600 text-sm mt-3">{error}</p>}<button disabled={loading} className="w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading ? 'Loading...' : 'Open Performance'}</button></form></div>;

  return <div className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Anjanay Heights CRM</p><h1 className="text-3xl font-bold text-[#1A365D] mt-1">📣 Campaign Performance</h1><p className="text-slate-600 mt-1">Measure enquiries generated by your tagged campaigns.</p></div><div className="flex gap-2"><a href="/admin" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Dashboard</a><button onClick={() => void load()} className="rounded-lg bg-[#1A365D] text-white px-4 py-2 text-sm font-semibold">Refresh</button></div></div><div className="grid sm:grid-cols-3 gap-4 mb-6"><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">Total enquiries</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{leads.length}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">Tagged enquiries</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{leads.filter(l => Boolean(l.utm_campaign)).length}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">Active campaign groups</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{campaigns.filter(c => c.campaign !== 'Unattributed').length}</p></div></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-4">Campaign</th><th className="px-5 py-4">Source</th><th className="px-5 py-4">Medium</th><th className="px-5 py-4">Enquiries</th><th className="px-5 py-4">Latest</th></tr></thead><tbody>{campaigns.map(c => <tr key={`${c.campaign}-${c.source}-${c.medium}`} className="border-t"><td className="px-5 py-4 font-semibold text-slate-900">{c.campaign}</td><td className="px-5 py-4">{c.source}</td><td className="px-5 py-4">{c.medium}</td><td className="px-5 py-4 font-bold text-[#1A365D]">{c.count}</td><td className="px-5 py-4 text-slate-500">{new Date(c.latest).toLocaleString('en-IN')}</td></tr>)}{campaigns.length === 0 && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">No enquiries yet.</td></tr>}</tbody></table></div><div className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">How to use this</h2><p className="text-sm text-slate-600 mt-1">Use Campaign Link Builder to create a unique UTM campaign for each ad, Reel, WhatsApp status or referral push. Then review this page weekly to see which campaigns actually generate enquiries.</p><a href="/admin/campaign-links" className="inline-block mt-4 text-sm font-semibold text-[#1A365D]">Open Campaign Link Builder →</a></div></div></div>;
}
