import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;name:string;phone:string;property_type?:string;location?:string;budget?:string;timeline?:string;requirement?:string;message?:string;created_at:string};
type Meta={status?:string;priority?:string;followUp?:string;nextAction?:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const phone=(v:string)=>{const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d};
export default function CRMWorkspace(){
 const [password,setPassword]=useState(()=>sessionStorage.getItem('crm_password')||'');const [leads,setLeads]=useState<Lead[]>([]);const [meta,setMeta]=useState<Record<string,Meta>>({});const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 async function load(){if(!password.trim()){setError('Enter CRM password.');return}setLoading(true);setError('');try{const h={Authorization:`Bearer ${password.trim()}`};const [lr,mr]=await Promise.all([fetch('/api/leads',{headers:h,cache:'no-store'}),fetch('/api/lead-meta',{headers:h,cache:'no-store'})]);const ld=await lr.json();const md=await mr.json().catch(()=>({}));if(!lr.ok)throw new Error(ld.error||'Unable to load CRM');setLeads(ld.leads||[]);setMeta(md.meta||{});sessionStorage.setItem('crm_password',password.trim());setOpen(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load CRM')}finally{setLoading(false)}}
 useEffect(()=>{if(password)void load()},[]);
 const t=today();
 const active=leads.filter(l=>!['Closed','Lost'].includes(meta[l.id]?.status||''));
 const due=active.filter(l=>meta[l.id]?.followUp===t);
 const overdue=active.filter(l=>{const d=meta[l.id]?.followUp;return !!d&&d<t});
 const hot=active.filter(l=>['Hot','Very Hot'].includes(meta[l.id]?.priority||''));
 const newest=[...active].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,8);
 const summary=useMemo(()=>({total:leads.length,active:active.length,due:due.length,overdue:overdue.length,hot:hot.length}),[leads,active,due,overdue,hot]);
 const whatsapp=(l:Lead)=>{const text=`Hi ${l.name||'there'}, thank you for your enquiry with Anjanay Heights. I am following up regarding your property requirement. Please let me know a convenient time to speak.`;window.open(`https://wa.me/${phone(l.phone)}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')};
 if(!open)return <div className="min-h-screen bg-[#F5F7FA] flex items-center justify-center p-4"><form onSubmit={e=>{e.preventDefault();void load()}} className="bg-white rounded-2xl shadow-xl p-7 w-full max-w-md"><p className="text-xs font-bold uppercase tracking-wider text-[#1A365D]">Anjanay Heights CRM</p><h1 className="text-3xl font-bold mt-2">Sales Control Center</h1><p className="text-gray-500 mt-2">One screen for today’s leads, overdue work, hot leads and quick actions.</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Dashboard password" className="w-full border rounded-xl px-4 py-3 mt-6"/><button disabled={loading} className="w-full mt-3 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading?'Loading…':'Open Control Center'}</button>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<a href="/admin" className="block text-center mt-4 text-sm font-semibold text-[#1A365D]">← Back to CRM</a></form></div>;
 return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-8"><div className="max-w-7xl mx-auto"><div className="flex flex-wrap justify-between items-center gap-3 mb-6"><div><a href="/admin" className="text-sm font-semibold text-[#1A365D]">← CRM Dashboard</a><h1 className="text-3xl font-bold text-[#1A365D] mt-2">Sales Control Center</h1><p className="text-gray-500">Live operational view of the CRM.</p></div><button onClick={()=>void load()} disabled={loading} className="bg-[#1A365D] text-white rounded-xl px-4 py-3 font-semibold">{loading?'Refreshing…':'↻ Refresh'}</button></div>{error&&<div className="mb-4 bg-red-50 text-red-700 rounded-xl p-3 text-sm">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6"><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Total leads</p><b className="text-3xl">{summary.total}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Active</p><b className="text-3xl">{summary.active}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Follow-up today</p><b className="text-3xl">{summary.due}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Overdue</p><b className="text-3xl text-red-600">{summary.overdue}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Hot / Very Hot</p><b className="text-3xl">{summary.hot}</b></div></div>
 <div className="grid lg:grid-cols-3 gap-4 mb-6"><a href="/admin/lead-quality" className="bg-white rounded-2xl border p-5 hover:shadow-md"><p className="text-2xl">🔥</p><h2 className="font-bold text-lg mt-2">Lead Quality</h2><p className="text-sm text-gray-500 mt-1">Prioritise high-intent leads and score them automatically.</p></a><a href="/admin/matches" className="bg-white rounded-2xl border p-5 hover:shadow-md"><p className="text-2xl">🎯</p><h2 className="font-bold text-lg mt-2">Match Properties</h2><p className="text-sm text-gray-500 mt-1">Find the best available inventory for each buyer requirement.</p></a><a href="/admin/followups" className="bg-white rounded-2xl border p-5 hover:shadow-md"><p className="text-2xl">📅</p><h2 className="font-bold text-lg mt-2">Follow-up Center</h2><p className="text-sm text-gray-500 mt-1">Move leads from contact to site visit, negotiation and close.</p></a></div>
 <div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-2xl border p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-[#1A365D]">🔴 Overdue</h2><p className="text-sm text-gray-500">Call these first.</p></div><span className="font-bold text-red-600">{overdue.length}</span></div><div className="mt-4 space-y-2">{overdue.slice(0,8).map(l=><div key={l.id} className="border rounded-xl p-3 flex justify-between gap-2"><div><b>{l.name||'Unnamed'}</b><p className="text-xs text-gray-500">{l.phone} · {meta[l.id]?.followUp}</p></div><div className="flex gap-2"><a href={`tel:${l.phone}`} className="bg-[#1A365D] text-white rounded-lg px-3 py-2 text-xs font-semibold">Call</a><button onClick={()=>whatsapp(l)} className="border rounded-lg px-3 py-2 text-xs font-semibold">WA</button></div></div>)}{!overdue.length&&<p className="text-sm text-gray-400 py-5">No overdue follow-ups.</p>}</div></section>
 <section className="bg-white rounded-2xl border p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-[#1A365D]">🔥 Hot Leads</h2><p className="text-sm text-gray-500">High-priority active opportunities.</p></div><span className="font-bold">{hot.length}</span></div><div className="mt-4 space-y-2">{hot.slice(0,8).map(l=><div key={l.id} className="border rounded-xl p-3 flex justify-between gap-2"><div><b>{l.name||'Unnamed'}</b><p className="text-xs text-gray-500">{l.location||'Location not set'} · {l.budget||'Budget not set'}</p><p className="text-xs text-gray-400">{meta[l.id]?.status||'New'} · {meta[l.id]?.nextAction||'Call'}</p></div><div className="flex gap-2"><a href={`tel:${l.phone}`} className="bg-[#1A365D] text-white rounded-lg px-3 py-2 text-xs font-semibold">Call</a><button onClick={()=>whatsapp(l)} className="border rounded-lg px-3 py-2 text-xs font-semibold">WA</button></div></div>)}{!hot.length&&<p className="text-sm text-gray-400 py-5">No active hot leads.</p>}</div></section></div>
 <section className="bg-white rounded-2xl border p-5 mt-5"><div className="flex justify-between items-center"><div><h2 className="text-xl font-bold text-[#1A365D]">🆕 Recent Active Leads</h2><p className="text-sm text-gray-500">Quick access to the newest enquiries.</p></div><a href="/admin" className="text-sm font-semibold text-[#1A365D]">Open full Leads →</a></div><div className="overflow-x-auto mt-3"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Lead</th><th>Requirement</th><th>Status</th><th>Follow-up</th><th>Action</th></tr></thead><tbody>{newest.map(l=><tr key={l.id} className="border-b"><td className="py-3 font-semibold">{l.name||'Unnamed'}<div className="text-xs text-gray-500">{l.phone}</div></td><td>{l.property_type||'—'}{l.location?` · ${l.location}`:''}<div className="text-xs text-gray-400">{l.budget||'Budget —'}</div></td><td>{meta[l.id]?.status||'New'}</td><td>{meta[l.id]?.followUp||'—'}</td><td><div className="flex gap-2"><a href={`tel:${l.phone}`} className="rounded-lg bg-[#1A365D] text-white px-3 py-2 text-xs">Call</a><button onClick={()=>whatsapp(l)} className="rounded-lg border px-3 py-2 text-xs">WA</button><a href={`/admin/matches?lead=${encodeURIComponent(l.id)}`} className="rounded-lg border px-3 py-2 text-xs">Match</a></div></td></tr>)}</tbody></table></div></section></div></div>;
}
