import React, { useEffect, useMemo, useState } from 'react';

type Lead = { id?: string | number; name?: string; phone?: string; location?: string; budget?: string; property_type?: string; timeline?: string; requirement?: string; status?: string };
type Meta = { priority?: string; nextAction?: string; followUp?: string; note?: string };
const today = () => new Date().toISOString().slice(0,10);
const score = (l: Lead) => {
 let s=0; if(l.phone)s+=15; if(l.name)s+=10; if(l.location)s+=15; if(l.budget)s+=15; if(l.timeline)s+=10; if(l.property_type)s+=10; if((l.requirement||'').length>=15)s+=10; if(/today|urgent|immediate|7 day|30 day/i.test(`${l.timeline||''} ${l.requirement||''}`))s+=10; if(/interested|site visit|negotiation/i.test(l.status||''))s+=5; return Math.min(100,s);
};
export default function DailyFollowUpQueue(){
 const [leads,setLeads]=useState<Lead[]>([]),[meta,setMeta]=useState<Record<string,Meta>>({}),[password,setPassword]=useState(''),[logged,setLogged]=useState(false),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 async function load(){if(!password)return;setLoading(true);try{const h={Authorization:`Bearer ${password}`};const [a,b]=await Promise.all([fetch(`/api/leads?_refresh=${Date.now()}`,{headers:h,cache:'no-store'}),fetch(`/api/lead-meta?_refresh=${Date.now()}`,{headers:h,cache:'no-store'})]);if(!a.ok||!b.ok)throw Error();const ld=await a.json(),md=await b.json();setLeads(Array.isArray(ld)?ld:ld.leads||[]);setMeta(md?.meta||md||{});setMsg('')}catch{setMsg('CRM data load nahi ho paaya.')}finally{setLoading(false)}}
 useEffect(()=>{if(logged)load()},[logged]);
 const queue=useMemo(()=>leads.map((lead,i)=>({lead,m:meta[String(lead.id??i)]||{},score:score(lead)})).filter(x=>!['Closed','Lost'].includes(x.lead.status||'')).filter(x=>x.m.followUp===today()||['Hot','Very Hot'].includes(x.m.priority||'')||x.score>=55).sort((a,b)=>(b.m.followUp===today()?30:0)+b.score-((a.m.followUp===today()?30:0)+a.score)),[leads,meta]);
 const wa=(p?:string)=>{const n=(p||'').replace(/\D/g,'');if(n)window.open(`https://wa.me/${n.length===10?'91'+n:n}`,'_blank')};
 async function follow(id?:string|number){if(id==null)return;const old=meta[String(id)]||{};const r=await fetch('/api/lead-meta',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({leadId:id,meta:{...old,priority:'Hot',nextAction:'Follow-up',followUp:today()}})});if(r.ok){setMsg('Follow-up updated.');load()}else setMsg('Follow-up update nahi hua.')}
 if(!logged)return <div className="p-6 max-w-md mx-auto"><h1 className="text-2xl font-bold mb-2">📋 Daily Follow-up Queue</h1><p className="text-sm opacity-70 mb-4">Aaj ke priority leads.</p><input className="w-full border rounded-lg p-3 mb-3" type="password" placeholder="Dashboard password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&setLogged(true)}/><button className="w-full rounded-lg p-3 bg-black text-white" onClick={()=>setLogged(true)}>Open Queue</button></div>;
 return <div className="p-4 md:p-6 space-y-5"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold">📋 Daily Follow-up Queue</h1><p className="text-sm opacity-70">Priority leads ko pehle call karo.</p></div><button className="border rounded-lg px-4 py-2" onClick={load}>{loading?'Loading…':'↻ Refresh'}</button></div>{msg&&<div className="border rounded-lg p-3 text-sm">{msg}</div>}<div className="grid grid-cols-2 gap-3"><div className="border rounded-xl p-4"><div className="text-sm opacity-60">Today's Queue</div><div className="text-2xl font-bold">{queue.length}</div></div><div className="border rounded-xl p-4"><div className="text-sm opacity-60">Hot / Very Hot</div><div className="text-2xl font-bold">{queue.filter(x=>['Hot','Very Hot'].includes(x.m.priority||'')).length}</div></div></div><div className="space-y-3">{queue.length===0?<div className="border rounded-xl p-6 text-center opacity-70">Aaj koi priority follow-up nahi hai.</div>:queue.map(({lead,m,score},i)=><div key={String(lead.id??i)} className="border rounded-xl p-4"><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><div className="font-bold">{lead.name||'Unnamed Lead'} <span className="text-sm font-normal opacity-60">· Score {score}</span></div><div className="text-sm opacity-70">{lead.phone||'No phone'} · {lead.location||'Location not set'}</div><div className="text-sm mt-1">{lead.property_type||'Property'} · {lead.budget||'Budget not set'} · {lead.timeline||'Timeline not set'}</div><div className="text-xs mt-2 opacity-60">{m.followUp===today()?'📅 Follow-up today':'🔥 High-intent lead'}</div></div><div className="flex flex-wrap gap-2"><a className="border rounded-lg px-3 py-2" href={`tel:${lead.phone||''}`}>📞 Call</a><button className="border rounded-lg px-3 py-2" onClick={()=>wa(lead.phone)}>💬 WhatsApp</button><button className="border rounded-lg px-3 py-2" onClick={()=>follow(lead.id)}>✓ Follow-up</button></div></div></div>)}</div></div>;
}
