import { useEffect, useMemo, useState } from 'react';

type Lead = { id: string; created_at: string; name: string; phone: string; email: string; form_name: string; lead_type: string; property_type: string; location: string; budget: string; timeline: string; requirement: string; message: string; };
type LeadMeta = { status: string; followUp: string; note: string; priority: string; nextAction: string };
const STATUSES = ['New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Closed', 'Lost'];
const PRIORITIES = ['Hot', 'Warm', 'Cold'];
const NEXT_ACTIONS = ['Call', 'WhatsApp', 'Site Visit', 'Meeting', 'Send Property Options', 'Follow-up', 'No Action'];
const META_KEY = 'anjanay-heights-lead-meta-v2';
const OLD_META_KEY = 'anjanay-heights-lead-meta-v1';
const DEFAULT_META: LeadMeta = { status: 'New', followUp: '', note: '', priority: 'Warm', nextAction: 'Call' };
function readMeta(): Record<string, LeadMeta> { try { const current = JSON.parse(localStorage.getItem(META_KEY) || '{}'); if (Object.keys(current).length) return current; const old = JSON.parse(localStorage.getItem(OLD_META_KEY) || '{}'); return old; } catch { return {}; } }
function buildWhatsAppMessage(lead: Lead) { const name = lead.name || 'there'; const details = [lead.property_type && `Property: ${lead.property_type}`, lead.location && `Location: ${lead.location}`, lead.budget && `Budget: ${lead.budget}`].filter(Boolean).join('\n'); return `Hi ${name}, thank you for your enquiry with Anjanay Heights.\n\n${details ? `${details}\n\n` : ''}I would be happy to help you with suitable property options. Please let me know a convenient time to speak.\n\nRegards,\nAnjanay Heights`; }
function phoneKey(phone: string) { return (phone || '').replace(/\D/g, '').replace(/^91(?=\d{10}$)/, ''); }
function whatsappPhone(phone: string) { const digits = (phone || '').replace(/\D/g, ''); if (digits.length === 10) return `91${digits}`; return digits; }
export default function LeadDashboard() {
  const [leads, setLeads] = useState<Lead[]>([]); const [password, setPassword] = useState(''); const [loggedIn, setLoggedIn] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('All'); const [priorityFilter, setPriorityFilter] = useState('All'); const [meta, setMeta] = useState<Record<string, LeadMeta>>({}); const [savingId, setSavingId] = useState('');
  useEffect(() => setMeta(readMeta()), []);
  function cacheMeta(next: Record<string, LeadMeta>) { setMeta(next); localStorage.setItem(META_KEY, JSON.stringify(next)); }
  function getMeta(id: string): LeadMeta { return { ...DEFAULT_META, ...(meta[id] || {}) }; }
  async function saveLeadMeta(id: string, nextMeta: LeadMeta) { const next = { ...meta, [id]: nextMeta }; cacheMeta(next); setSavingId(id); try { const response = await fetch('/api/lead-meta', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${password}` }, body: JSON.stringify({ leadId: id, meta: nextMeta }) }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.error || 'Cloud save failed'); } } catch (err) { setError(err instanceof Error ? `${err.message}. Local copy kept.` : 'Cloud save failed. Local copy kept.'); } finally { setSavingId(''); } }
  function updateLeadMeta(id: string, patch: Partial<LeadMeta>) { void saveLeadMeta(id, { ...getMeta(id), ...patch }); }
  async function loadLeads() { setLoading(true); setError(''); try { const [leadsResponse, metaResponse] = await Promise.all([fetch('/api/leads', { headers: { Authorization: `Bearer ${password}` } }), fetch('/api/lead-meta', { headers: { Authorization: `Bearer ${password}` } })]); const leadsResult = await leadsResponse.json(); if (!leadsResponse.ok) throw new Error(leadsResult.error || 'Unable to load leads'); let serverMeta: Record<string, LeadMeta> = {}; if (metaResponse.ok) { const metaResult = await metaResponse.json(); serverMeta = metaResult.meta || {}; } const localMeta = readMeta(); const mergedMeta = { ...localMeta, ...serverMeta }; setLeads(leadsResult.leads || []); cacheMeta(mergedMeta); setLoggedIn(true); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load leads'); } finally { setLoading(false); } }
  function handleLogin(event: React.FormEvent) { event.preventDefault(); if (!password.trim()) { setError('Please enter your dashboard password.'); return; } void loadLeads(); }
  function exportCsv() { const rows = filteredLeads.map((lead) => { const m = getMeta(lead.id); return [lead.name, lead.phone, lead.email, lead.form_name, lead.lead_type, lead.property_type, lead.location, lead.budget, lead.timeline, m.priority, m.status, m.nextAction, m.followUp, m.note, lead.message || lead.requirement]; }); const csv = [['Name','Phone','Email','Source','Lead Type','Property','Location','Budget','Timeline','Priority','Status','Next Action','Follow-up','Note','Requirement / Message'], ...rows].map((row) => row.map((v) => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `anjanay-heights-leads-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }
  const today = new Date().toISOString().slice(0, 10);
  const duplicatePhones = useMemo(() => { const counts: Record<string, number> = {}; leads.forEach((l) => { const p = phoneKey(l.phone); if (p) counts[p] = (counts[p] || 0) + 1; }); return counts; }, [leads]);
  const filteredLeads = useMemo(() => leads.filter((lead) => { const m = getMeta(lead.id); const haystack = [lead.name, lead.phone, lead.email, lead.form_name, lead.lead_type, lead.property_type, lead.location, lead.budget, lead.timeline, lead.requirement, lead.message, m.note, m.nextAction, m.priority].join(' ').toLowerCase(); const special = search === '__OVERDUE__' ? Boolean(m.followUp && m.followUp < today && !['Closed','Lost'].includes(m.status)) : haystack.includes(search.toLowerCase()); return special && (statusFilter === 'All' || m.status === statusFilter) && (priorityFilter === 'All' || m.priority === priorityFilter); }).sort((a,b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()), [leads, search, statusFilter, priorityFilter, meta, today]);
  const statusCounts = STATUSES.reduce<Record<string, number>>((acc, status) => { acc[status] = leads.filter((lead) => getMeta(lead.id).status === status).length; return acc; }, {});
  const priorityCounts = PRIORITIES.reduce<Record<string, number>>((acc, priority) => { acc[priority] = leads.filter((lead) => getMeta(lead.id).priority === priority).length; return acc; }, {});
  const followUpToday = leads.filter((lead) => { const m = getMeta(lead.id); return m.followUp === today && !['Closed','Lost'].includes(m.status); }).length;
  const overdueFollowUps = leads.filter((lead) => { const m = getMeta(lead.id); return m.followUp && m.followUp < today && !['Closed','Lost'].includes(m.status); }).length;
  const todayWork = leads.filter((lead) => { const m = getMeta(lead.id); return (m.followUp === today || (m.nextAction !== 'No Action' && m.status === 'New')) && !['Closed','Lost'].includes(m.status); }).length;
  const duplicateLeadCount = Object.values(duplicatePhones).filter((count) => count > 1).length;
  const activeLeads = leads.filter((l) => !['Closed','Lost'].includes(getMeta(l.id).status)).length;
  const conversionRate = leads.length ? Math.round((statusCounts.Closed / leads.length) * 100) : 0;
  const progressedLeads = leads.filter((l) => !['New','Lost'].includes(getMeta(l.id).status)).length;
  if (!loggedIn) return <div className="min-h-screen bg-[#F9F9F7] flex items-center justify-center px-4"><form onSubmit={handleLogin} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><h1 className="text-3xl font-bold text-[#1A365D] text-center">Anjanay Heights</h1><p className="text-gray-500 text-center mt-2">Lead Management Dashboard</p><label className="block mt-8 mb-2 font-semibold">Dashboard Password</label><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter password" className="w-full border rounded-xl px-4 py-3" />{error && <p className="text-red-600 text-sm mt-3">{error}</p>}<button type="submit" disabled={loading} className="w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading ? 'Loading...' : 'Open Dashboard'}</button></form></div>;
  return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-8"><div className="max-w-7xl mx-auto"><div className="flex flex-col md:flex-row md:justify-between gap-4 mb-8"><div><h1 className="text-3xl font-bold text-[#1A365D]">Anjanay Heights</h1><p className="text-gray-500 mt-1">Lead Management Dashboard</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="bg-white border border-[#1A365D] text-[#1A365D] px-4 py-3 rounded-xl font-semibold">Export CSV</button><button onClick={() => { setLoggedIn(false); setPassword(''); }} className="bg-white border text-gray-700 px-4 py-3 rounded-xl font-semibold">Logout</button><button onClick={() => void loadLeads()} disabled={loading} className="bg-[#1A365D] text-white px-5 py-3 rounded-xl font-semibold disabled:opacity-60">{loading ? 'Refreshing...' : 'Refresh Leads'}</button></div></div>
      {error && <div className="bg-red-50 text-red-700 rounded-xl px-4 py-3 mb-5 text-sm">{error}</div>}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3 mb-6"><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Total</p><p className="text-2xl font-bold text-[#1A365D]">{leads.length}</p></div>{STATUSES.slice(0,5).map((status) => <button key={status} onClick={() => { setStatusFilter(status); setPriorityFilter('All'); setSearch(''); }} className={`text-left bg-white rounded-2xl p-4 shadow ${statusFilter === status ? 'ring-2 ring-[#1A365D]' : ''}`}><p className="text-gray-500 text-sm">{status}</p><p className="text-2xl font-bold text-[#1A365D]">{statusCounts[status] || 0}</p></button>)}<button onClick={() => { setStatusFilter('Closed'); setPriorityFilter('All'); setSearch(''); }} className="text-left bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Closed</p><p className="text-2xl font-bold text-[#1A365D]">{statusCounts.Closed || 0}</p></button></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"><button onClick={() => { setSearch(today); setStatusFilter('All'); setPriorityFilter('All'); }} className="bg-white rounded-2xl p-4 shadow text-left"><p className="text-gray-500 text-sm">Follow-up today</p><p className="text-2xl font-bold text-[#1A365D]">{followUpToday}</p></button><button onClick={() => { setSearch('__OVERDUE__'); setStatusFilter('All'); setPriorityFilter('All'); }} className="bg-white rounded-2xl p-4 shadow text-left"><p className="text-gray-500 text-sm">Overdue</p><p className="text-2xl font-bold text-[#1A365D]">{overdueFollowUps}</p></button><button onClick={() => { setSearch(''); setStatusFilter('All'); setPriorityFilter('All'); }} className="bg-white rounded-2xl p-4 shadow text-left"><p className="text-gray-500 text-sm">Today's work</p><p className="text-2xl font-bold text-[#1A365D]">{todayWork}</p></button><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Active leads</p><p className="text-2xl font-bold text-[#1A365D]">{activeLeads}</p></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Conversion</p><p className="text-2xl font-bold text-[#1A365D]">{conversionRate}%</p><p className="text-xs text-gray-400">Closed / total</p></div><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Progressed</p><p className="text-2xl font-bold text-[#1A365D]">{progressedLeads}</p><p className="text-xs text-gray-400">Past New stage</p></div><button onClick={() => { setSearch(''); setStatusFilter('All'); setPriorityFilter('All'); }} className="bg-white rounded-2xl p-4 shadow text-left"><p className="text-gray-500 text-sm">Duplicate phones</p><p className="text-2xl font-bold text-[#1A365D]">{duplicateLeadCount}</p><p className="text-xs text-gray-400">Click to review in lead cards</p></button><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Hot leads</p><p className="text-2xl font-bold text-[#1A365D]">{priorityCounts.Hot || 0}</p></div></div>
      <div className="grid grid-cols-3 gap-3 mb-5">{PRIORITIES.map((priority) => <button key={priority} onClick={() => { setPriorityFilter(priority); setStatusFilter('All'); }} className={`bg-white rounded-2xl p-4 shadow text-left ${priorityFilter === priority ? 'ring-2 ring-[#1A365D]' : ''}`}><p className="text-gray-500 text-sm">{priority} priority</p><p className="text-2xl font-bold text-[#1A365D]">{priorityCounts[priority] || 0}</p></button>)}</div>
      {overdueFollowUps > 0 && <button onClick={() => setSearch('__OVERDUE__')} className="w-full text-left bg-amber-50 border border-amber-200 text-amber-800 rounded-xl px-4 py-3 mb-5">⚠️ <strong>{overdueFollowUps}</strong> overdue follow-up{overdueFollowUps > 1 ? 's' : ''}. Review the leads below and update the next action.</button>}
      <div className="bg-white rounded-2xl shadow p-4 mb-6 grid md:grid-cols-[1fr_auto_auto_auto] gap-3"><input value={search === '__OVERDUE__' ? '' : search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, phone, location, budget..." className="w-full border rounded-xl px-4 py-3" /><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="border rounded-xl px-4 py-3 bg-white"><option>All</option>{STATUSES.map((s) => <option key={s}>{s}</option>)}</select><select value={priorityFilter} onChange={(e) => setPriorityFilter(e.target.value)} className="border rounded-xl px-4 py-3 bg-white"><option>All</option>{PRIORITIES.map((p) => <option key={p}>{p}</option>)}</select><button onClick={() => { setSearch(''); setStatusFilter('All'); setPriorityFilter('All'); }} className="border rounded-xl px-4 py-3 bg-white font-semibold">Clear Filters</button></div>
      <div className="flex justify-between items-center mb-3 text-sm text-gray-500"><span>Showing {filteredLeads.length} of {leads.length} leads</span></div>
      {filteredLeads.length === 0 ? <div className="bg-white rounded-2xl shadow p-10 text-center text-gray-500">No leads found.</div> : <div className="space-y-4">{filteredLeads.map((lead) => { const current = getMeta(lead.id); const normalized = phoneKey(lead.phone); const isDuplicate = normalized && duplicatePhones[normalized] > 1; const waNumber = whatsappPhone(lead.phone); const whatsappUrl = waNumber ? `https://wa.me/${waNumber}?text=${encodeURIComponent(buildWhatsAppMessage(lead))}` : ''; const matchUrl = `/admin/matches?lead=${encodeURIComponent(lead.id)}`; return <div key={lead.id} className="bg-white rounded-2xl shadow p-5"><div className="flex flex-col lg:flex-row lg:justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-[#1A365D]">{lead.name || 'Unknown Lead'}</h2><span className={`text-xs font-bold px-2 py-1 rounded-full ${current.priority === 'Hot' ? 'bg-red-100 text-red-700' : current.priority === 'Warm' ? 'bg-orange-100 text-orange-700' : 'bg-slate-100 text-slate-600'}`}>{current.priority}</span>{isDuplicate && <span className="text-xs font-bold px-2 py-1 rounded-full bg-purple-100 text-purple-700">Duplicate phone</span>}</div><p className="text-gray-500 text-sm">{lead.form_name || 'Lead'} · {new Date(lead.created_at).toLocaleString('en-IN')}</p></div><div className="flex flex-wrap gap-2"><a href={matchUrl} className="bg-[#1A365D] text-white px-4 py-2 rounded-lg font-semibold">Matched Properties</a>{lead.phone && <a href={`tel:${lead.phone}`} className="bg-green-600 text-white px-4 py-2 rounded-lg font-semibold">Call</a>}{whatsappUrl && <a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="bg-green-500 text-white px-4 py-2 rounded-lg font-semibold">WhatsApp Follow-up</a>}</div></div>
          <div className="grid md:grid-cols-3 gap-4 mt-5"><div><p className="text-xs text-gray-400">PHONE</p><p className="font-semibold">{lead.phone || '-'}</p></div><div><p className="text-xs text-gray-400">LEAD TYPE</p><p className="font-semibold">{lead.lead_type || '-'}</p></div><div><p className="text-xs text-gray-400">PROPERTY</p><p className="font-semibold">{lead.property_type || '-'}</p></div><div><p className="text-xs text-gray-400">LOCATION</p><p className="font-semibold">{lead.location || '-'}</p></div><div><p className="text-xs text-gray-400">BUDGET</p><p className="font-semibold">{lead.budget || '-'}</p></div><div><p className="text-xs text-gray-400">TIMELINE</p><p className="font-semibold">{lead.timeline || '-'}</p></div><div className="md:col-span-3"><p className="text-xs text-gray-400">REQUIREMENT / MESSAGE</p><p className="font-semibold">{lead.requirement || lead.message || '-'}</p></div></div>
          <div className="mt-5 pt-5 border-t grid md:grid-cols-4 gap-3"><div><label className="text-xs font-semibold text-gray-500">PRIORITY</label><select value={current.priority} onChange={(e) => updateLeadMeta(lead.id, { priority: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 bg-white">{PRIORITIES.map((p) => <option key={p}>{p}</option>)}</select></div><div><label className="text-xs font-semibold text-gray-500">STATUS</label><select value={current.status} onChange={(e) => updateLeadMeta(lead.id, { status: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 bg-white">{STATUSES.map((s) => <option key={s}>{s}</option>)}</select></div><div><label className="text-xs font-semibold text-gray-500">NEXT ACTION</label><select value={current.nextAction} onChange={(e) => updateLeadMeta(lead.id, { nextAction: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 bg-white">{NEXT_ACTIONS.map((a) => <option key={a}>{a}</option>)}</select></div><div><label className="text-xs font-semibold text-gray-500">FOLLOW-UP DATE</label><input type="date" value={current.followUp} onChange={(e) => updateLeadMeta(lead.id, { followUp: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2" /></div><div className="md:col-span-4"><label className="text-xs font-semibold text-gray-500">NOTE {savingId === lead.id ? '(Saving...)' : ''}</label><input value={current.note} onChange={(e) => updateLeadMeta(lead.id, { note: e.target.value })} onBlur={(e) => updateLeadMeta(lead.id, { note: e.target.value })} placeholder="Call result / next action" className="mt-1 w-full border rounded-lg px-3 py-2" /></div></div>
        </div>; })}</div>}
    </div></div>;
}
