import { useEffect, useMemo, useState } from 'react';

type Lead = { id: string; property_type: string; location: string; budget: string };
type Property = { id: string; title: string; propertyType: string; location: string; price: string; minBudget: number | null; maxBudget: number | null; area: string; bedrooms: string; status: string; description: string };

function normalize(value: string) { return (value || '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim(); }
function budgetNumber(value: string) { const n = Number((value || '').replace(/[^0-9.]/g, '')); if (!n) return null; const lower = normalize(value); if (lower.includes('crore') || lower.includes(' cr')) return n * 10000000; if (lower.includes('lakh') || lower.includes(' lac')) return n * 100000; return n; }
function score(lead: Lead, p: Property) { let s = 0; const l = normalize(lead.location); const pl = normalize(p.location); const type = normalize(lead.property_type); if (l && l !== 'not specified' && (pl.includes(l) || l.includes(pl))) s += 55; if (type && type !== 'not specified' && normalize(p.propertyType).includes(type)) s += 25; const b = budgetNumber(lead.budget); if (b && p.minBudget != null && p.maxBudget != null && b >= p.minBudget && b <= p.maxBudget) s += 20; else if (b && ((p.maxBudget != null && b <= p.maxBudget) || (p.minBudget != null && b >= p.minBudget))) s += 10; return s; }

export default function LeadPropertyMatches({ lead, password }: { lead: Lead; password: string }) {
  const [properties, setProperties] = useState<Property[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!open) return; fetch('/api/properties', { headers: { Authorization: `Bearer ${password}` } }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to load properties'); setProperties(d.properties || []); }).catch(e => setError(e.message || 'Unable to load properties')); }, [open, password]);
  const matches = useMemo(() => properties.filter(p => p.status === 'Available').map(p => ({ p, score: score(lead, p) })).filter(x => x.score >= 10).sort((a,b) => b.score - a.score).slice(0, 5), [properties, lead]);
  return <div className="mt-3"><button onClick={() => setOpen(v => !v)} className="border rounded-lg px-3 py-2 text-sm font-semibold text-[#1A365D]">{open ? 'Hide property matches' : 'Find matching properties'}</button>{open && <div className="mt-3 rounded-xl bg-[#F8FAFC] border p-3">{error ? <p className="text-red-600 text-sm">{error}</p> : matches.length === 0 ? <p className="text-sm text-gray-500">No suitable available properties found. Add real listings to Property Inventory.</p> : <div className="space-y-2">{matches.map(({p,score}) => <div key={p.id} className="bg-white border rounded-xl p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold">{p.title}</p><p className="text-sm text-[#1A365D]">{p.location}</p><p className="text-xs text-gray-500">{p.propertyType} · {p.price || 'Price not set'}{p.area ? ` · ${p.area}` : ''}</p></div><span className="text-xs font-bold px-2 py-1 rounded-full bg-gray-100 h-fit">{score}% match</span></div></div>)}</div>}</div>}</div>;
}
