import { useState } from 'react';

type Property = { id:string; title:string; propertyType:string; location:string; price:string; minBudget:number|null; maxBudget:number|null; area:string; bedrooms:string; status:'Available'|'Hold'|'Sold'|'Inactive'; description:string; createdAt:string };
type Snapshot = { pathname:string; uploadedAt:string; properties:Property[] };

export default function PropertyRecovery() {
  const [password,setPassword]=useState(''); const [loggedIn,setLoggedIn]=useState(false); const [snapshots,setSnapshots]=useState<Snapshot[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  async function load(){ setLoading(true); setError(''); try { const r=await fetch('/api/property-history',{headers:{Authorization:`Bearer ${password}`},cache:'no-store'}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Unable to load history'); setSnapshots(d.snapshots||[]); setLoggedIn(true); } catch(e:any){setError(e.message||'Unable to load history');} finally{setLoading(false);} }
  async function restore(snapshot:Snapshot){ if(!window.confirm(`Restore this backup containing ${snapshot.properties.length} properties? Current inventory will be backed up first.`)) return; setLoading(true); setError(''); setMessage(''); try { const r=await fetch('/api/property-history',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({action:'restore',properties:snapshot.properties})}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Restore failed'); setMessage(`Restored ${d.properties.length} properties successfully.`); } catch(e:any){setError(e.message||'Restore failed');} finally{setLoading(false);} }
  if(!loggedIn) return <div className="min-h-screen bg-[#F9F9F7] flex items-center justify-center p-6"><form onSubmit={e=>{e.preventDefault();void load();}} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-7"><div className="text-xs font-bold tracking-[0.2em] text-[#1A365D] uppercase">Anjanay Heights</div><h1 className="text-2xl font-bold mt-2">Inventory Recovery</h1><p className="text-gray-500 text-sm mt-2">Find previous property inventory snapshots and safely restore one.</p><input type="password" placeholder="Dashboard password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full border rounded-xl px-4 py-3 mt-5"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button disabled={!password||loading} className="w-full mt-3 rounded-xl bg-[#1A365D] text-white py-3 font-semibold">{loading?'Checking…':'Open Recovery'}</button></form></div>;
  return <div className="min-h-screen bg-[#F9F9F7] p-4 md:p-8"><div className="max-w-5xl mx-auto"><div className="flex items-center justify-between gap-3 mb-6"><div><button onClick={()=>window.location.href='/admin/properties'} className="text-sm text-[#1A365D] font-semibold">← Property Inventory</button><h1 className="text-3xl font-bold mt-2">Inventory Recovery</h1><p className="text-gray-500">{snapshots.length} saved inventory snapshots found.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border bg-white px-4 py-3 font-semibold">↻ Refresh</button></div>{message&&<div className="bg-green-50 border border-green-200 text-green-800 rounded-xl p-4 mb-4">{message} <button onClick={()=>window.location.href='/admin/properties'} className="font-bold underline ml-2">Open Inventory</button></div>}{error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 mb-4">{error}</div>}<div className="space-y-4">{snapshots.map(s=><div key={s.pathname} className="bg-white border rounded-2xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="font-bold text-lg">Backup: {new Date(s.uploadedAt).toLocaleString('en-IN')}</p><p className="text-gray-600 mt-1">Contains <strong>{s.properties.length}</strong> properties</p><p className="text-sm text-gray-500 mt-1">{s.properties.map(p=>p.title).join(' · ') || 'Empty inventory'}</p></div><button onClick={()=>void restore(s)} disabled={loading||s.properties.length<=1} className="rounded-xl bg-[#1A365D] text-white px-5 py-3 font-semibold disabled:opacity-40">{s.properties.length<=1?'Not useful':'Restore this backup'}</button></div>)}{!snapshots.length&&<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">No property backups are available.</div>}</div></div></div>;
}
