import { useEffect, useState } from 'react';

type Property = { id:string; title:string; location:string; videoUrl?:string; photos?:string[]; status:string };
const SESSION_KEY='anjanay-heights-crm-password';
function getSession(){try{return sessionStorage.getItem(SESSION_KEY)||sessionStorage.getItem('crm_password')||'';}catch{return '';}}
function saveSession(value:string){try{sessionStorage.setItem(SESSION_KEY,value);sessionStorage.setItem('crm_password',value);}catch{}}
function validVideoUrl(value:string){if(!value.trim())return true;try{const u=new URL(value.trim());return ['youtube.com','www.youtube.com','youtu.be','youtube-nocookie.com','www.youtube-nocookie.com','vimeo.com','www.vimeo.com'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch{return false;}}
export default function PropertyVideoManager(){
 const[password,setPassword]=useState(()=>getSession());const[loggedIn,setLoggedIn]=useState(()=>Boolean(getSession()));const[properties,setProperties]=useState<Property[]>([]);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState('');const[error,setError]=useState('');
 async function load(token=getSession()){const clean=String(token||'').trim();if(!clean){setLoggedIn(false);setError('Please enter the CRM password.');return;}setLoading(true);setError('');try{const auth=await fetch('/api/auth',{headers:{Authorization:`Bearer ${clean}`},cache:'no-store'});if(!auth.ok)throw new Error('Incorrect CRM password.');const r=await fetch(`/api/properties?_refresh=${Date.now()}`,{headers:{Authorization:`Bearer ${clean}`,'Cache-Control':'no-cache'},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load inventory.');saveSession(clean);setPassword(clean);setProperties(d.properties||[]);setLoggedIn(true);}catch(e:any){setError(e.message||'Unable to load inventory.');}finally{setLoading(false);}}
 useEffect(()=>{const t=getSession();if(t)void load(t);},[]);
 async function saveVideo(p:Property,value:string){if(!validVideoUrl(value)){setError('Use a valid YouTube, YouTube Shorts, or Vimeo URL.');return;}setSaving(p.id);setError('');try{const r=await fetch('/api/properties',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({action:'upsert',id:p.id,title:p.title,location:p.location,status:p.status,videoUrl:value.trim(),photos:p.photos||[]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save video.');setProperties(d.properties||[]);}catch(e:any){setError(e.message||'Unable to save video.');}finally{setSaving('');}}
 if(!loggedIn)return <div className="min-h-screen bg-[#F9F9F7] flex items-center justify-center p-6"><div className="w-full max-w-md bg-white rounded-2xl shadow-xl p-7"><div className="text-xs font-bold tracking-[0.2em] text-[#1A365D] uppercase">Anjanay Heights</div><h1 className="text-2xl font-bold mt-2">Property Video Manager</h1><p className="text-gray-500 text-sm mt-2">Add only genuine property/project videos to existing CRM inventory.</p><input type="password" placeholder="Dashboard password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(password)}} className="w-full border rounded-xl px-4 py-3 mt-5"/><button type="button" onClick={()=>void load(password)} disabled={loading} className="w-full mt-3 rounded-xl bg-[#1A365D] text-white py-3 font-semibold">{loading?'Checking…':'Open Video Manager'}</button>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div></div>;
 return <div className="min-h-screen bg-[#F9F9F7] p-4 md:p-8"><div className="max-w-6xl mx-auto"><button type="button" onClick={()=>window.location.href='/admin/properties'} className="text-sm text-[#1A365D] font-semibold">← Property Inventory</button><div className="flex items-center justify-between gap-3 mt-2"><div><h1 className="text-3xl font-bold">Property Video Manager</h1><p className="text-gray-500 mt-1">Existing inventory only · genuine public video links · no fabricated media</p></div><button type="button" onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-3 font-semibold">↻ Refresh</button></div>{error&&<div className="mt-4 rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 mt-6">{properties.map(p=>{const id=`video-${p.id}`;return <div key={p.id} className="bg-white border rounded-2xl p-5"><div className="flex flex-col md:flex-row md:items-center gap-4"><div className="w-20 h-20 rounded-xl overflow-hidden bg-slate-100 shrink-0">{p.photos?.[0]?<img src={p.photos[0]} alt={p.title} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-2xl">🏠</div>}</div><div className="min-w-0 flex-1"><h2 className="font-bold text-lg">{p.title}</h2><p className="text-sm text-gray-500">{p.location}</p><label htmlFor={id} className="block text-xs font-semibold text-gray-600 mt-3 mb-1">Verified video URL</label><input id={id} defaultValue={p.videoUrl||''} placeholder="https://www.youtube.com/watch?v=..." className="w-full border rounded-xl px-4 py-3"/><p className="text-xs text-gray-400 mt-1">Accepted: YouTube, YouTube Shorts, Vimeo. Leave blank if no genuine video exists.</p></div><button type="button" onClick={()=>{const el=document.getElementById(id) as HTMLInputElement|null;if(el)void saveVideo(p,el.value)}} disabled={saving===p.id} className="rounded-xl bg-[#1A365D] text-white px-5 py-3 font-semibold shrink-0">{saving===p.id?'Saving…':'Save Video'}</button></div>{p.videoUrl&&<div className="mt-3 rounded-xl bg-green-50 border border-green-200 p-3 text-sm"><span className="font-semibold text-green-800">Video saved:</span> <a href={p.videoUrl} target="_blank" rel="noreferrer" className="underline break-all">{p.videoUrl}</a></div>}</div>})}</div></div></div>;
}