import { useCallback, useEffect, useMemo, useState } from 'react';

type Lead={id:string;name:string;phone:string;property_type?:string;location?:string;budget?:string;timeline?:string;requirement?:string;message?:string;created_at:string};
type Meta={status?:string;priority?:string;followUp?:string;nextAction?:string;note?:string;assignedTo?:string};

const repsKey='anjanay-heights-sales-reps';
const phone=(v:string)=>{const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d};
const scoreLead=(l:Lead)=>{let s=10;const text=`${l.property_type||''} ${l.location||''} ${l.budget||''} ${l.timeline||''} ${l.requirement||''} ${l.message||''}`.toLowerCase();if(/hospital|commercial|land|shop/.test(text))s+=20;if(/150|100|50|1 cr|1cr|crore/.test(text))s+=25;if(/today|immediate|urgent|7 day|15 day|30 day/.test(text))s+=20;if((l.requirement||l.message||'').trim())s+=10;if(l.location)s+=5;return Math.min(100,s)};
const priority=(s:number)=>s>=75?'Very Hot':s>=55?'Hot':s>=30?'Warm':'Cold';

export default function SalesTeamPerformance(){
 const [password,setPassword]=useState(()=>sessionStorage.getItem('crm_password')||'');
 const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({});
 const [reps,setReps]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(repsKey)||'null')||['Sales Desk','Seema']}catch{return ['Sales Desk','Seema']}});
 const [newRep,setNewRep]=useState(''); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(''); const [error,setError]=useState(''); const [lastSync,setLastSync]=useState<Date|null>(null);
 const load=useCallback(async()=>{if(!password.trim()){setError('Enter CRM password.');return}setLoading(true);setError('');try{const h={Authorization:`Bearer ${password.trim()}`};const [lr,mr]=await Promise.all([fetch(`/api/leads?refresh=${Date.now()}`,{headers:h,cache:'no-store'}),fetch(`/api/lead-meta?refresh=${Date.now()}`,{headers:h,cache:'no-store'})]);const ld=await lr.json();const md=await mr.json().catch(()=>({}));if(!lr.ok)throw new Error(ld.error||'Unable to load CRM');setLeads(ld.leads||[]);setMeta(md.meta||{});sessionStorage.setItem('crm_password',password.trim());setLastSync(new Date())}catch(e){setError(e instanceof Error?e.message:'Unable to load CRM')}finally{setLoading(false)}},[password]);
 useEffect(()=>{if(password)void load()},[password,load]);
 useEffect(()=>{localStorage.setItem(repsKey,JSON.stringify(reps))},[reps]);
 async function saveMeta(leadId:string,patch:Meta,note:string){setSaving(leadId);setError('');try{const h={Authorization:`Bearer ${password.trim()}`,'Content-Type':'application/json'};const r=await fetch('/api/lead-meta',{method:'POST',headers:h,body:JSON.stringify({leadId,meta:{...(meta[leadId]||{}),...patch},activity:{action:'Sales assignment',note}})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save assignment');setMeta(prev=>({...prev,[leadId]:d.meta}));setLastSync(new Date())}catch(e){setError(e instanceof Error?e.message:'Unable to save assignment')}finally{setSaving('')}}
 const active=useMemo(()=>leads.filter(l=>!['Closed','Lost'].includes(meta[l.id]?.status||'')),[leads,meta]);
 const assigned=useMemo(()=>active.filter(l=>meta[l.id]?.assignedTo),[active,meta]);
 const unassigned=useMemo(()=>active.filter(l=>!meta[l.id]?.assignedTo),[active,meta]);
 const stats=useMemo(()=>reps.map(rep=>{const mine=leads.filter(l=>meta[l.id]?.assignedTo===rep);const closed=mine.filter(l=>meta[l.id]?.status==='Closed').length;const lost=mine.filter(l=>meta[l.id]?.status==='Lost').length;const visits=mine.filter(l=>meta[l.id]?.status==='Site Visit').length;const negotiation=mine.filter(l=>meta[l.id]?.status==='Negotiation').length;const hot=mine.filter(l=>['Hot','Very Hot'].includes(meta[l.id]?.priority||priority(scoreLead(l)))).length;const value=mine.filter(l=>!['Closed','Lost'].includes(meta[l.id]?.status||'')).reduce((sum,l)=>sum+(Number(String(l.budget||'').replace(/[^0-9.]/g,''))||0),0);return {rep,mine:mine.length,closed,lost,visits,negotiation,hot,value,conversion:mine.length?Math.round((closed/mine.length)*100):0}}),[reps,leads,meta]);
 async function autoAssign(){if(!reps.length||!unassigned.length)return;setLoading(true);setError('');try{const counts=Object.fromEntries(reps.map(r=>[r,active.filter(l=>meta[l.id]?.assignedTo===r).length]));const ordered=[...unassigned].sort((a,b)=>scoreLead(b)-scoreLead(a));for(const lead of ordered){const rep=[...reps].sort((a,b)=>counts[a]-counts[b])[0];await saveMeta(lead.id,{assignedTo:rep},`Auto-assigned ${lead.name||'lead'} to ${rep} using balanced round-robin with lead priority.`);counts[rep]++;}await load()}finally{setLoading(false)}}
 function addRep(){const n=newRep.trim();if(!n||reps.includes(n))return;setReps([...reps,n]);setNewRep('')}
 function removeRep(rep:string){if(active.some(l=>meta[l.id]?.assignedTo===rep))return setError(`Reassign ${rep}'s active leads before removing this salesperson.`);setReps(reps.filter(r=>r!==rep))}
 if(!password.trim())return <div className="min-h-screen bg-[#F5F7FA] flex items-center justify-center p-4"><form onSubmit={e=>{e.preventDefault();void load()}} className="bg-white rounded-2xl shadow-xl p-7 w-full max-w-md"><p className="text-xs font-bold uppercase tracking-wider text-[#1A365D]">Anjanay Heights CRM</p><h1 className="text-3xl font-bold mt-2">Sales Team Control</h1><p className="text-gray-500 mt-2">Assignment and salesperson performance dashboard.</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Dashboard password" className="w-full border rounded-xl px-4 py-3 mt-6"/><button disabled={loading} className="w-full mt-3 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading?'Loading…':'Open Team Dashboard'}</button>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<a href="/admin/workspace" className="block text-center mt-4 text-sm font-semibold text-[#1A365D]">← Back to Control Center</a></form></div>;
 return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-8"><div className="max-w-7xl mx-auto"><div className="flex flex-wrap justify-between items-center gap-3 mb-6"><div><a href="/admin/workspace" className="text-sm font-semibold text-[#1A365D]">← Sales Control Center</a><h1 className="text-3xl font-bold text-[#1A365D] mt-2">👥 Sales Team Performance</h1><p className="text-gray-500">Automatic lead assignment + salesperson conversion tracking.</p>{lastSync&&<p className="text-xs text-gray-400 mt-1">Synced {lastSync.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</p>}</div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="border bg-white rounded-xl px-4 py-3 font-semibold">↻ Sync</button><button onClick={()=>void autoAssign()} disabled={loading||!unassigned.length||!reps.length} className="bg-[#1A365D] text-white rounded-xl px-4 py-3 font-semibold">⚡ Auto-assign {unassigned.length}</button></div></div>{error&&<div className="mb-4 bg-red-50 text-red-700 rounded-xl p-3 text-sm">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Active leads</p><b className="text-3xl">{active.length}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Assigned</p><b className="text-3xl">{assigned.length}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Unassigned</p><b className="text-3xl text-amber-600">{unassigned.length}</b></div><div className="bg-white rounded-2xl border p-4"><p className="text-xs text-gray-500">Salespeople</p><b className="text-3xl">{reps.length}</b></div></div>
 <section className="bg-white rounded-2xl border p-5 mb-5"><div className="flex flex-wrap justify-between gap-3 items-center"><div><h2 className="text-xl font-bold text-[#1A365D]">Salespeople</h2><p className="text-sm text-gray-500">Performance is calculated from the same CRM lead stages.</p></div><div className="flex gap-2"><input value={newRep} onChange={e=>setNewRep(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addRep()}}} placeholder="Add salesperson" className="border rounded-xl px-3 py-2"/><button onClick={addRep} className="border rounded-xl px-4 py-2 font-semibold">+ Add</button></div></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3 pr-3">Salesperson</th><th>Leads</th><th>Hot</th><th>Site visits</th><th>Negotiation</th><th>Closed</th><th>Conversion</th><th>Active budget signal</th><th></th></tr></thead><tbody>{stats.map(s=><tr key={s.rep} className="border-b"><td className="py-3 pr-3 font-bold">{s.rep}</td><td>{s.mine}</td><td>{s.hot}</td><td>{s.visits}</td><td>{s.negotiation}</td><td>{s.closed}</td><td><span className="font-bold">{s.conversion}%</span></td><td>₹{s.value.toLocaleString('en-IN')}</td><td><button onClick={()=>removeRep(s.rep)} className="text-xs text-red-600" disabled={s.mine>0}>Remove</button></td></tr>)}</tbody></table></div></section>
 <section className="bg-white rounded-2xl border p-5"><div className="flex justify-between items-center gap-3"><div><h2 className="text-xl font-bold text-[#1A365D]">Lead Assignment</h2><p className="text-sm text-gray-500">New active leads can be distributed automatically by workload and priority.</p></div></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3 pr-3">Lead</th><th>Priority</th><th>Stage</th><th>Location</th><th>Budget</th><th>Assigned to</th><th>Action</th></tr></thead><tbody>{[...active].sort((a,b)=>scoreLead(b)-scoreLead(a)).slice(0,50).map(l=>{const m=meta[l.id]||{};const p=m.priority||priority(scoreLead(l));return <tr key={l.id} className="border-b align-top"><td className="py-3 pr-3 font-semibold">{l.name||'Unnamed'}<div className="text-xs text-gray-500">{l.phone}</div></td><td><span className="font-semibold">{p}</span><div className="text-[11px] text-gray-400">Score {scoreLead(l)}/100</div></td><td>{m.status||'New'}</td><td>{l.location||'—'}</td><td>{l.budget||'—'}</td><td><select value={m.assignedTo||''} onChange={e=>void saveMeta(l.id,{assignedTo:e.target.value||undefined},`${l.name||'Lead'} assigned to ${e.target.value||'Unassigned'}.`)} className="border rounded-lg px-2 py-2"><option value="">Unassigned</option>{reps.map(r=><option key={r}>{r}</option>)}</select></td><td><a href={`tel:${l.phone}`} className="bg-[#1A365D] text-white rounded-lg px-3 py-2 text-xs font-semibold">Call</a></td></tr>})}</tbody></table>{!active.length&&<p className="text-sm text-gray-400 py-6">No active leads.</p>}</div></section></div></div>;
}
