import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;name?:string;phone?:string;property_type?:string;location?:string;budget?:string;source?:string;created_at?:string};
type Meta={status?:string;priority?:string;nextAction?:string;followUp?:string;dealValue?:string;siteVisitDateTime?:string;assignedSalesperson?:string};
const SESSION_KEY='anjanay-heights-crm-password';
const money=(v?:string)=>v?`₹${v}`:'—';
const rank=(p?:string)=>p==='Very Hot'?4:p==='Hot'?3:p==='Warm'?2:1;
const dateText=(v?:string)=>{if(!v)return 'Not scheduled';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});};
const isOverdue=(v?:string)=>{if(!v)return false;const d=new Date(v);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now();};

export default function SalesCockpit(){
 const [password]=useState(()=>sessionStorage.getItem(SESSION_KEY)||sessionStorage.getItem('crm_password')||'');
 const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!password){setLoading(false);return;}try{const h={Authorization:`Bearer ${password}`};const [a,b]=await Promise.all([fetch('/api/leads?refresh='+Date.now(),{headers:h,cache:'no-store'}),fetch('/api/lead-meta?refresh='+Date.now(),{headers:h,cache:'no-store'})]);const l=await a.json(),m=await b.json();if(!a.ok)throw new Error(l.error||'Unable to load leads');setLeads(l.leads||[]);setMeta(m.meta||{});}catch(e){setError(e instanceof Error?e.message:'Unable to load sales cockpit')}finally{setLoading(false)}})()},[password]);
 const rows=useMemo(()=>leads.map(lead=>({lead,m:meta[lead.id]||{}})).filter(x=>x.m.status!=='Closed'&&x.m.status!=='Lost').sort((a,b)=>{const ao=isOverdue(a.m.followUp),bo=isOverdue(b.m.followUp);if(ao!==bo)return ao?-1:1;const pr=rank(b.m.priority)-rank(a.m.priority);if(pr)return pr;return String(a.m.followUp||'').localeCompare(String(b.m.followUp||''));}),[leads,meta]);
 const overdue=rows.filter(x=>isOverdue(x.m.followUp)).length; const hot=rows.filter(x=>rank(x.m.priority)>=3).length; const visits=rows.filter(x=>x.m.status==='Site Visit').length; const negotiation=rows.filter(x=>x.m.status==='Negotiation').length;
 if(!password)return <div className="min-h-screen bg-[#F5F7FA] flex items-center justify-center p-6"><div className="bg-white border rounded-2xl p-8 max-w-md text-center"><h1 className="text-2xl font-bold text-[#1A365D]">Sales Cockpit Locked</h1><p className="text-gray-500 mt-2">Open the CRM and sign in first.</p><a href="/admin" className="inline-block mt-5 bg-[#1A365D] text-white rounded-xl px-5 py-3 font-semibold">Open CRM</a></div></div>;
 return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-7"><div className="max-w-7xl mx-auto"><div className="flex flex-wrap justify-between gap-3 mb-6"><div><a href="/admin" className="text-sm font-semibold text-[#1A365D]">← CRM Dashboard</a><p className="text-xs uppercase tracking-widest text-[#C2A36B] font-bold mt-3">Anjanay Heights</p><h1 className="text-3xl font-bold text-[#1A365D]">Daily Sales Cockpit</h1><p className="text-gray-500">Aaj kis lead par action lena hai — ek screen par.</p></div><div className="flex gap-2"><a href="/admin/sales-journey" className="border rounded-xl px-4 py-2.5 font-semibold bg-white">🚀 Sales Journey</a><button onClick={()=>location.reload()} className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">↻ Refresh</button></div></div>
 {error&&<div className="bg-red-50 text-red-700 rounded-xl p-3 mb-4">{error}</div>}
 {loading?<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">Loading real CRM leads…</div>:!rows.length?<div className="bg-white border rounded-2xl p-10 text-center"><b className="text-[#1A365D]">No active real leads yet.</b><p className="text-gray-500 mt-2">New website enquiries will automatically appear here.</p></div>:<>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-400">ACTIVE</p><b className="text-2xl text-[#1A365D]">{rows.length}</b></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-400">HOT+</p><b className="text-2xl text-[#1A365D]">{hot}</b></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-400">OVERDUE</p><b className="text-2xl text-red-600">{overdue}</b></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-400">VISIT / NEGOTIATION</p><b className="text-2xl text-[#1A365D]">{visits} / {negotiation}</b></div></div>
 <div className="grid lg:grid-cols-2 gap-4">{rows.map(({lead,m})=>{const wa=lead.phone?`https://wa.me/${lead.phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${lead.name||''}, this is Anjanay Heights. Following up on your ${lead.property_type||'property'} requirement.`)}`:'#';return <div key={lead.id} className={`bg-white border rounded-2xl p-5 ${isOverdue(m.followUp)?'border-red-200':''}`}><div className="flex justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="text-xs font-bold px-2 py-1 rounded-full bg-gray-100">{m.priority||'Warm'}</span><span className="text-xs font-semibold px-2 py-1 rounded-full bg-[#F4F7FB] text-[#1A365D]">{m.status||'New'}</span>{isOverdue(m.followUp)&&<span className="text-xs font-bold px-2 py-1 rounded-full bg-red-50 text-red-700">OVERDUE</span>}</div><h2 className="text-xl font-bold text-[#1A365D] mt-2">{lead.name||'Unnamed lead'}</h2><p className="text-sm text-gray-500">{lead.phone||'No phone'} · {lead.property_type||'Property'} · {lead.location||'NCR'}</p></div><div className="text-right"><p className="text-xs text-gray-400">DEAL</p><b>{money(m.dealValue)}</b></div></div><div className="grid sm:grid-cols-3 gap-2 mt-4 text-sm"><div className="bg-[#F8FAFC] rounded-xl p-3"><span className="text-xs text-gray-400 block">NEXT ACTION</span><b>{m.nextAction||'Call'}</b></div><div className="bg-[#F8FAFC] rounded-xl p-3"><span className="text-xs text-gray-400 block">FOLLOW-UP</span><b>{dateText(m.followUp)}</b></div><div className="bg-[#F8FAFC] rounded-xl p-3"><span className="text-xs text-gray-400 block">SOURCE</span><b>{lead.source||'Website'}</b></div></div><div className="flex flex-wrap gap-2 mt-4"><a href={`tel:${lead.phone||''}`} className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">📞 Call</a><a href={wa} target="_blank" rel="noreferrer" className="bg-emerald-600 text-white rounded-xl px-4 py-2.5 font-semibold">💬 WhatsApp</a><a href={`/admin/sales-journey?lead=${encodeURIComponent(lead.id)}`} className="border rounded-xl px-4 py-2.5 font-semibold">Open Journey →</a></div></div>})}</div></>}
 </div></div>;
}
