import { useMemo, useState } from 'react';

type Lead = { id: string; created_at: string; name: string; form_name: string; lead_type: string; source?: string; utm_source?: string; utm_medium?: string; utm_campaign?: string };
type Meta = { status?: string };
const STAGES = ['New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Closed', 'Lost'];
const SOURCE_NAMES = ['Website', 'WhatsApp', 'Meta', 'Google', 'Referral', '99acres', 'MagicBricks', 'Other'];
function sourceOf(l: Lead) { const raw = String(l.source || l.utm_source || l.utm_medium || l.form_name || l.lead_type || '').toLowerCase(); if (raw.includes('whatsapp') || raw === 'wa') return 'WhatsApp'; if (raw.includes('facebook') || raw.includes('instagram') || raw.includes('meta')) return 'Meta'; if (raw.includes('google')) return 'Google'; if (raw.includes('referral') || raw.includes('refer')) return 'Referral'; if (raw.includes('99acres')) return '99acres'; if (raw.includes('magicbricks')) return 'MagicBricks'; if (raw.includes('website') || raw.includes('property-lead') || raw.includes('callback')) return 'Website'; return 'Other'; }
export default function SourceConversionFunnel() { const [password,setPassword]=useState(''); const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({}); const [loggedIn,setLoggedIn]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const token=`${Date.now()}`;const [lr,mr]=await Promise.all([fetch(`/api/leads?_refresh=${token}`,{headers:{Authorization:`Bearer ${password}`},cache:'no-store'}),fetch(`/api/lead-meta?_refresh=${token}`,{headers:{Authorization:`Bearer ${password}`},cache:'no-store'})]);const l=await lr.json();if(!lr.ok)throw new Error(l.error||'Unable to load leads');const m=mr.ok?await mr.json():{};setLeads(l.leads||[]);setMeta(m.meta||{});setLoggedIn(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load funnel')}finally{setLoading(false)}}
 const groups=useMemo(()=>{const map:Record<string,{name:string;total:number;stages:Record<string,number>}>={};leads.forEach(l=>{const source=sourceOf(l);const campaign=l.utm_campaign?.trim()||'Unattributed';const key=`${campaign}|||${source}`;if(!map[key])map[key]={name:campaign, total:0, stages:Object.fromEntries(STAGES.map(s=>[s,0]))};map[key].total++;const status=meta[l.id]?.status||'New';if(status in map[key].stages)map[key].stages[status]++});return Object.values(map).sort((a,b)=>b.total-a.total)},[leads,meta]);
 const totals=useMemo(()=>Object.fromEntries(STAGES.map(s=>[s,leads.filter(l=>(meta[l.id]?.status||'New')===s).length])),[leads,meta]);
 if(!loggedIn)return <div className="min-h-screen bg-slate-50 flex items-center justify-center px-4"><form onSubmit={e=>{e.preventDefault();void load()}} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><h1 className="text-3xl font-bold text-[#1A365D] text-center">Source Conversion Funnel</h1><p className="text-gray-500 text-center mt-2">See which sources move leads toward closure.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Dashboard password" className="w-full border rounded-xl px-4 py-3 mt-8"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button disabled={loading} className="w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading?'Loading...':'Open Funnel'}</button></form></div>;
 return <div className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Anjanay Heights CRM</p><h1 className="text-3xl font-bold text-[#1A365D] mt-1">📈 Source Conversion Funnel</h1><p className="text-slate-600 mt-1">Compare enquiry → contact → site visit → negotiation → closed.</p></div><div className="flex gap-2"><a href="/admin/source-analytics" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Source Analytics</a><button onClick={()=>void load()} disabled={loading} className="rounded-lg bg-[#1A365D] text-white px-4 py-2 text-sm font-semibold">{loading?'Refreshing...':'Refresh'}</button></div></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3 mb-6">{STAGES.map(s=><div key={s} className="bg-white rounded-2xl p-4 shadow-sm"><p className="text-xs text-slate-500">{s}</p><p className="text-2xl font-bold text-[#1A365D] mt-1">{totals[s]||0}</p></div>)}</div><div className="space-y-4">{groups.map((g,i)=>{const source=SOURCE_NAMES.find(s=>s===sourceOf(leads.find(l=>(l.utm_campaign?.trim()||'Unattributed')===g.name)!))||'Other';const active=g.total-g.stages.Closed-g.stages.Lost;const closeRate=Math.round((g.stages.Closed/g.total)*100);return <div key={`${g.name}-${source}-${i}`} className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold text-lg text-slate-900">{g.name}</h2><p className="text-sm text-slate-500">Source: {source} · {g.total} enquiries</p></div><div className="text-right"><p className="text-xs text-slate-500">Closed rate</p><p className="text-2xl font-bold text-[#1A365D]">{closeRate}%</p></div></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2 mt-4">{STAGES.map(s=><div key={s} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{s}</p><p className="font-bold text-slate-900 mt-1">{g.stages[s]||0}</p></div>)}</div><p className="text-xs text-slate-500 mt-3">Active pipeline: {active < 0 ? 0 : active} · Site Visit: {g.stages['Site Visit']||0} · Negotiation: {g.stages.Negotiation||0}</p></div>})}</div>{!groups.length&&<div className="bg-white rounded-2xl p-8 text-center text-slate-500">No enquiries found.</div>}</div></div> }
