import { useEffect, useMemo, useState } from 'react';

type Lead = {
  id: string; created_at: string; name: string; phone: string; email: string; lead_type: string;
  property_type: string; location: string; budget: string; timeline: string; requirement: string; message: string;
};
type CallLog = { id: string; at: string; outcome: string; note: string };
type Meta = { status: string; followUp: string; note: string; priority: string; nextAction: string; propertyType: string; location: string; budget: string; timeline: string; callHistory?: CallLog[] };
const DEFAULT: Meta = { status:'New', followUp:'', note:'', priority:'Warm', nextAction:'Call', propertyType:'', location:'', budget:'', timeline:'', callHistory:[] };
const OUTCOMES = ['Connected','Not Connected','Interested','Not Interested','Callback'];
const priorityRank: Record<string, number> = { Hot:0, Warm:1, Cold:2 };
function cleanPhone(phone:string){ const d=(phone||'').replace(/\D/g,''); return d.length===10?`91${d}`:d; }
function today(){ return new Date().toISOString().slice(0,10); }
function tomorrow(){ const d=new Date(); d.setDate(d.getDate()+1); return d.toISOString().slice(0,10); }

export default function TelecallingCRM(){
  const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({});
  const [password,setPassword]=useState(''); const [loggedIn,setLoggedIn]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const [selected,setSelected]=useState(''); const [outcome,setOutcome]=useState('Connected'); const [note,setNote]=useState(''); const [search,setSearch]=useState(''); const [saving,setSaving]=useState(false);
  const getMeta=(id:string):Meta=>({...DEFAULT,...(meta[id]||{}),callHistory:(meta[id]?.callHistory||[])});
  async function load(){ if(loading)return; setLoading(true); setError(''); const token=`${Date.now()}-${Math.random()}`; try{ const headers={Authorization:`Bearer ${password}`,'Cache-Control':'no-cache'}; const [lr,mr]=await Promise.all([fetch(`/api/leads?_refresh=${token}`,{headers,cache:'no-store'}),fetch(`/api/lead-meta?_refresh=${token}`,{headers,cache:'no-store'})]); const ld=await lr.json(); const md=mr.ok?await mr.json():{meta:{}}; if(!lr.ok)throw new Error(ld.error||'Unable to load leads'); setLeads(ld.leads||[]); setMeta(md.meta||{}); setLoggedIn(true); }catch(e){setError(e instanceof Error?e.message:'Unable to load leads');}finally{setLoading(false);} }
  async function saveCall(lead:Lead){ setSaving(true); setError(''); const m=getMeta(lead.id); const log:CallLog={id:`call-${Date.now()}`,at:new Date().toISOString(),outcome,note:note.trim()}; const nextHistory=[...(m.callHistory||[]),log].slice(-30); let status=m.status,nextAction='Follow-up',followUp=tomorrow(),priority=m.priority; if(outcome==='Interested'){status='Interested';nextAction='Follow-up';followUp=tomorrow();priority='Hot';} else if(outcome==='Not Interested'){status='Lost';nextAction='No Action';followUp='';priority='Cold';} else if(outcome==='Callback'){status='Contacted';nextAction='Call';followUp=tomorrow();priority='Warm';} else if(outcome==='Not Connected'){status='Contacted';nextAction='Call';followUp=tomorrow();priority='Warm';} else {status='Contacted';nextAction='Follow-up';followUp=tomorrow();priority=m.priority==='Hot'?'Hot':'Warm';}
    const next={...m,status,nextAction,followUp,priority,callHistory:nextHistory,note:note.trim()||m.note}; setMeta(x=>({...x,[lead.id]:next})); try{const r=await fetch('/api/lead-meta',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({leadId:lead.id,meta:next}),cache:'no-store'}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data.error||'Call save failed'); setNote(''); setSelected('');}catch(e){setError(e instanceof Error?e.message:'Call save failed.');}finally{setSaving(false);} }
  const queue=useMemo(()=>{ const t=today(),q=leads.filter(l=>{const m=getMeta(l.id); const hay=[l.name,l.phone,l.location,l.property_type,l.budget,l.requirement,l.message].join(' ').toLowerCase(); const searchOk=!search||hay.includes(search.toLowerCase()); return searchOk && m.status!=='Closed' && m.status!=='Lost' && (!m.followUp||m.followUp<=t||m.status==='New'); }); return q.sort((a,b)=>{const pa=priorityRank[getMeta(a.id).priority]??9,pb=priorityRank[getMeta(b.id).priority]??9; return pa-pb||new Date(b.created_at).getTime()-new Date(a.created_at).getTime();}); },[leads,meta,search]);
  const selectedLead=leads.find(l=>l.id===selected); const counts=useMemo(()=>({total:leads.length,hot:leads.filter(l=>getMeta(l.id).priority==='Hot'&&getMeta(l.id).status!=='Closed'&&getMeta(l.id).status!=='Lost').length,today:leads.filter(l=>{const m=getMeta(l.id);return m.followUp===today()&&m.status!=='Closed'&&m.status!=='Lost';}).length,queue:queue.length}),[leads,meta,queue]);
  if(!loggedIn)return <div className="min-h-screen bg-[#F9F9F7] flex items-center justify-center px-4"><form onSubmit={e=>{e.preventDefault();if(password.trim())void load();else setError('Please enter your dashboard password.')}} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><h1 className="text-3xl font-bold text-[#1A365D] text-center">📞 Telecalling CRM</h1><p className="text-gray-500 text-center mt-2">Anjanay Heights</p><label className="block mt-8 mb-2 font-semibold">Dashboard Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full border rounded-xl px-4 py-3" placeholder="Enter password"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button disabled={loading} className="w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading?'Loading...':'Open Telecalling CRM'}</button></form></div>;
  return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-8"><div className="max-w-7xl mx-auto"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-6"><div><h1 className="text-3xl font-bold text-[#1A365D]">📞 Telecalling CRM</h1><p className="text-gray-500 mt-1">Daily calling queue, outcomes and follow-ups</p></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="bg-[#1A365D] text-white px-4 py-3 rounded-xl font-semibold">{loading?'Refreshing...':'↻ Refresh'}</button><button onClick={()=>window.location.href='/admin'} className="bg-white border px-4 py-3 rounded-xl font-semibold">← Leads</button></div></div>
    {error&&<div className="bg-red-50 text-red-700 rounded-xl px-4 py-3 mb-5 text-sm">{error}</div>}
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Total Leads</p><p className="text-2xl font-bold text-[#1A365D]">{counts.total}</p></div><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Call Queue</p><p className="text-2xl font-bold text-[#1A365D]">{counts.queue}</p></div><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Follow-up Today</p><p className="text-2xl font-bold text-[#1A365D]">{counts.today}</p></div><div className="bg-white rounded-2xl p-4 shadow"><p className="text-gray-500 text-sm">Hot Leads</p><p className="text-2xl font-bold text-[#1A365D]">{counts.hot}</p></div></div>
    <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, location, budget..." className="w-full bg-white border rounded-xl px-4 py-3 mb-5"/>
    <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><div className="space-y-3">{queue.length===0?<div className="bg-white rounded-2xl p-8 text-center text-gray-500">No leads in the calling queue.</div>:queue.map(lead=>{const m=getMeta(lead.id);return <div key={lead.id} className={`bg-white rounded-2xl p-4 shadow ${m.priority==='Hot'?'ring-2 ring-red-200':''}`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-lg text-[#1A365D]">{lead.name||'Unnamed Lead'}</h2><p className="text-sm text-gray-600">{lead.phone} · {lead.location||'Location not specified'}</p><p className="text-sm mt-1">{lead.property_type||'Property not specified'} {lead.budget?`· ${lead.budget}`:''}</p></div><span className="text-xs font-bold px-2 py-1 rounded-full bg-slate-100">{m.priority}</span></div><div className="flex flex-wrap gap-2 mt-4"><a href={`tel:${lead.phone}`} className="bg-[#1A365D] text-white px-4 py-2 rounded-lg font-semibold">📞 Call</a><a target="_blank" rel="noreferrer" href={`https://wa.me/${cleanPhone(lead.phone)}`} className="bg-green-600 text-white px-4 py-2 rounded-lg font-semibold">WhatsApp</a><button onClick={()=>{setSelected(lead.id);setOutcome('Connected');setNote('')}} className="border border-[#1A365D] text-[#1A365D] px-4 py-2 rounded-lg font-semibold">Log Call</button></div>{m.followUp&&<p className="text-xs text-gray-500 mt-3">Next follow-up: {m.followUp}</p>}</div>})}</div>
      <div className="bg-white rounded-2xl shadow p-5 h-fit lg:sticky lg:top-4">{selectedLead?<><h2 className="text-xl font-bold text-[#1A365D]">Log call: {selectedLead.name||'Lead'}</h2><p className="text-sm text-gray-500 mt-1">{selectedLead.phone}</p><label className="block mt-5 mb-2 font-semibold">Call outcome</label><select value={outcome} onChange={e=>setOutcome(e.target.value)} className="w-full border rounded-xl px-3 py-3">{OUTCOMES.map(x=><option key={x}>{x}</option>)}</select><label className="block mt-4 mb-2 font-semibold">Call notes</label><textarea value={note} onChange={e=>setNote(e.target.value)} rows={5} className="w-full border rounded-xl px-3 py-3" placeholder="What did the lead say? Next step?"/><p className="text-xs text-gray-500 mt-2">After saving: Interested → Hot + follow-up tomorrow; Callback/Not Connected → Warm + call tomorrow; Connected → follow-up tomorrow.</p><button disabled={saving} onClick={()=>void saveCall(selectedLead)} className="w-full mt-4 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{saving?'Saving...':'Save Call Outcome'}</button><button onClick={()=>setSelected('')} className="w-full mt-2 border rounded-xl py-3 font-semibold">Cancel</button><div className="mt-6 border-t pt-4"><h3 className="font-bold">Recent call history</h3>{getMeta(selectedLead.id).callHistory?.slice().reverse().slice(0,5).map(c=><div key={c.id} className="text-sm border-b py-3"><b>{c.outcome}</b> · {new Date(c.at).toLocaleString()}<p className="text-gray-600 mt-1">{c.note||'No note'}</p></div>)}</div></>:<div className="text-center text-gray-500 py-8">Select <b>Log Call</b> on a lead to record the call outcome.</div>}</div></div></div></div>;
}
