import { get, list } from '@vercel/blob';
import { createHmac } from 'node:crypto';

const candidates = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
function header(req:any,n:string){const h=req?.headers;return h&&typeof h.get==='function'?h.get(n)||'':h?.[n.toLowerCase()]||h?.[n]||'';}
function token(){const p=process.env.DASHBOARD_PASSWORD||'';return p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';}
function authorized(req:any){const p=process.env.DASHBOARD_PASSWORD||'';const a=header(req,'authorization');const c=String(header(req,'cookie')||'').split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith('ah_crm_session='))?.split('=').slice(1).join('=')||'';return Boolean((p&&a===`Bearer ${p}`)||(token()&&decodeURIComponent(c)===token()));}
async function withAuth<T>(fn:(a:any)=>Promise<T>){let e:any;for(const a of [{},...candidates]){try{return await fn(a)}catch(x){e=x;if(!/access|token|credential|unauthorized|forbidden/i.test(String((x as any)?.message||x)))throw x}}throw e;}
async function read(url:string){const r:any=await withAuth(a=>get(url,{access:'private',useCache:false,...a}));return r?.stream?await new Response(r.stream).json():null;}
const norm=(v:any)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function amount(v:any){let s=String(v||'').toLowerCase().replace(/,/g,'').replace(/₹|rs\.?/g,'').trim();const n=parseFloat(s.replace(/[^0-9.]/g,''));if(!Number.isFinite(n))return null;if(/crore|cr\b/.test(s))return n*10000000;if(/lakh|lac\b|l\b/.test(s))return n*100000;return n;}
function overlap(lead:any,p:any){const b=amount(lead.budget);const min=Number(p.minBudget);const max=Number(p.maxBudget);if(b===null||(!Number.isFinite(min)&&!Number.isFinite(max)))return false;const lo=Number.isFinite(min)?min:0;const hi=Number.isFinite(max)?max:Infinity;return b>=lo*0.75&&b<=hi*1.25;}
function score(lead:any,p:any){let s=10;const reasons:string[]=[];const lt=norm(lead.property_type),pt=norm(p.propertyType);const ll=norm(lead.location),pl=norm(p.location);if(lt&&pt&&(pt===lt||pt.includes(lt)||lt.includes(pt))){s+=35;reasons.push('Property type matches');}if(ll&&pl&&(pl===ll||pl.includes(ll)||ll.includes(pl))){s+=35;reasons.push('Location matches');}if(overlap(lead,p)){s+=20;reasons.push('Budget fits inventory range');}else if(lead.budget){reasons.push('Budget fit needs confirmation');}const terms=[...new Set(norm(`${lead.requirement} ${lead.timeline}`).split(' ').filter(x=>x.length>3))];if(terms.some(x=>norm(`${p.title} ${p.description}`).includes(x))){s+=10;reasons.push('Requirement details align');}return {matchScore:Math.min(100,s),matchReasons:reasons};}
export default async function handler(req:any,res:any){if(!authorized(req))return res.status(401).json({error:'Unauthorized'});try{const id=String(req?.query?.leadId||'');if(!id)return res.status(400).json({error:'leadId is required'});const lr=await withAuth(a=>list({prefix:'leads/',...a}));let lead:any=null;for(const b of lr.blobs){try{const x=await read(b.url);if(x?.id===id){lead=x;break}}catch{}}if(!lead)return res.status(404).json({error:'Lead not found'});const pr=await withAuth(a=>list({prefix:'properties/',...a}));const properties=(await Promise.all(pr.blobs.map(async b=>{try{return await read(b.url)}catch{return null}}))).filter((p:any)=>p&&String(p.status||'Available').toLowerCase()==='available').map((p:any)=>{const scored=score(lead,p);return {id:p.id,title:p.title,propertyType:p.propertyType,location:p.location,price:p.price,minBudget:p.minBudget,maxBudget:p.maxBudget,area:p.area,bedrooms:p.bedrooms,photos:Array.isArray(p.photos)?p.photos.slice(0,3):[],matchScore:scored.matchScore,matchReasons:scored.matchReasons};}).sort((a:any,b:any)=>b.matchScore-a.matchScore).slice(0,10);return res.status(200).setHeader('Cache-Control','no-store').json({lead,properties});}catch(e){console.error('lead-match error',e);return res.status(500).json({error:'Unable to match properties.'});}}
