import { get, list, put, del } from '@vercel/blob';
import { createHmac } from 'node:crypto';

type Property={id:string;title:string;propertyType:string;location:string;price:string;minBudget:number|null;maxBudget:number|null;area:string;bedrooms:string;status:'Available'|'Hold'|'Sold'|'Inactive';description:string;createdAt:string;photos?:string[]};
const PATH='crm/properties.json', ITEM_PREFIX='crm/properties/item-', PHOTO_PREFIX='crm/properties/photos/', RECOVERY_MARKER='crm/properties/recovery-seeded-v3.json';
const STATUSES=new Set(['Available','Hold','Sold','Inactive']);
const RECOVERY_PROPERTIES:Property[]=[
{id:'recovered-aminabad-710',title:'710 sq ft Flat',propertyType:'Flat',location:'Sector 1, Aminabad, Greater Noida',price:'₹40 Lakhs',minBudget:4000000,maxBudget:4000000,area:'710 sq ft',bedrooms:'',status:'Available',description:'Flat in Sector 1, Aminabad, Greater Noida. Seller: Arun.',createdAt:'2026-09-10T00:00:00.000Z'},
{id:'recovered-haridwar-110-bigha',title:'110 Bigha Commercial Land',propertyType:'Commercial Land',location:'Haridwar',price:'₹47 Lakhs per Bigha',minBudget:517000000,maxBudget:517000000,area:'110 bigha',bedrooms:'',status:'Available',description:'110 bigha commercial land in Haridwar. Demand: ₹47 Lakhs per bigha. Approx. total value: ₹51.70 Cr. Seller: Arun.',createdAt:'2026-09-10T00:00:00.000Z'},
{id:'recovered-faridabad-hospital',title:'100 Beds Hospital',propertyType:'Hospital',location:'Faridabad',price:'₹55 Cr · 3000 sq yard',minBudget:550000000,maxBudget:550000000,area:'3000 sq yard',bedrooms:'',status:'Available',description:'Operational 100-bed hospital. Seller: Rohit Sharma. Seller contact is kept private and should be shared directly when needed.',createdAt:'2026-09-10T00:00:00.000Z'},
{id:'researched-express-astra',title:'Express Astra',propertyType:'Flat',location:'Sector 1, Greater Noida West',price:'₹1.42 Cr onwards',minBudget:14200000,maxBudget:null,area:'',bedrooms:'2/3/4 BHK',status:'Available',description:'Verified researched project listing. RERA: UPRERAPRJ479698; Phase 2 RERA: UPRERAPRJ229234. Builder sales contact: +91 93130 32920. Current price and availability must be reconfirmed before marketing.',createdAt:'2026-09-12T00:00:00.000Z'},
{id:'researched-gaurs-7th-avenue',title:'Gaurs 7th Avenue',propertyType:'Flat',location:'Gaur City, Greater Noida West',price:'₹90 Lakhs onwards',minBudget:9000000,maxBudget:null,area:'',bedrooms:'2/3 BHK',status:'Available',description:'Verified researched project listing. RERA: UPRERAPRJ6695. Sales contact: +91 85060 10010. Current price and availability must be reconfirmed before marketing.',createdAt:'2026-09-12T00:00:00.000Z'},
{id:'researched-gaurs-14th-avenue',title:'Gaurs 14th Avenue',propertyType:'Flat',location:'Gaur City, Greater Noida West',price:'₹95 Lakhs onwards',minBudget:9500000,maxBudget:null,area:'',bedrooms:'2/3 BHK',status:'Available',description:'Verified researched project listing. RERA: UPRERAPRJ6742. Sales contact: +91 85060 10010. Current price and availability must be reconfirmed before marketing.',createdAt:'2026-09-12T00:00:00.000Z'}];
const blobAuthCandidates:Record<string,string>[]=[{},...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
function blobAuthError(e:unknown){const x=e as any;return /BlobAccessError|access denied|valid token|credentials|unauthorized|forbidden/i.test(`${x?.name||x?.constructor?.name||''} ${x?.message||''}`)}
async function withBlobAuth<T>(op:(auth:Record<string,string>)=>Promise<T>):Promise<T>{let last:any=new Error('No Vercel Blob credentials configured.');for(const auth of blobAuthCandidates){try{return await op(auth)}catch(e){last=e;if(!blobAuthError(e))throw e}}throw last}
function getHeader(req:any,name:string){const h=req?.headers;if(h&&typeof h.get==='function')return h.get(name)||'';const v=h?.[name.toLowerCase()]??h?.[name];return Array.isArray(v)?v[0]||'':v||''}
function getCookie(req:any,name:string){const raw=String(getHeader(req,'cookie')||'');const m=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(`${name}=`));return m?decodeURIComponent(m.slice(name.length+1)):''}
function sessionToken(){const p=process.env.DASHBOARD_PASSWORD||'';return p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):''}
function authorized(req:any){const p=process.env.DASHBOARD_PASSWORD||'';return Boolean((p&&getHeader(req,'authorization')===`Bearer ${p}`)||(sessionToken()&&getCookie(req,'ah_crm_session')===sessionToken()))}
function send(res:any,status:number,body:unknown){return res.status(status).setHeader('Cache-Control','no-store').setHeader('Pragma','no-cache').json(body)}
function parseBody(req:any){const b=req?.body;if(b&&typeof b==='object'&&!Buffer.isBuffer(b))return b;if(typeof b==='string')try{return JSON.parse(b)}catch{}return {}}
async function readLegacy(){const r=await withBlobAuth(a=>get(PATH,{access:'private',...a}));if(!r?.stream)throw new Error('Blob read failed');const d=JSON.parse(await new Response(r.stream).text());if(!Array.isArray(d))throw new Error('Property inventory data is invalid');return d as Property[]}
async function readItems(){const blobs:any[]=[];let cursor:string|undefined;do{const p=await withBlobAuth(a=>list({prefix:ITEM_PREFIX,cursor,...a}));blobs.push(...(p.blobs||[]));cursor=p.hasMore?p.cursor:undefined}while(cursor);const out:Property[]=[];for(const b of blobs){try{const r=await withBlobAuth(a=>get(b.url||b.pathname,{access:'private',...a}));if(r?.stream){const v=JSON.parse(await new Response(r.stream).text());if(v?.id)out.push(v)}}catch(e){if(!blobAuthError(e))throw e}}return out}
async function readProperties(){const items=await readItems();if(items.length)return items;try{return await readLegacy()}catch(e){if(blobAuthError(e))throw e;return []}}
function itemPath(id:string){return `${ITEM_PREFIX}${encodeURIComponent(id)}.json`}
async function ensureItems(ps:Property[]){for(const p of ps)await withBlobAuth(a=>put(itemPath(p.id),JSON.stringify(p),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}))}
async function seed(){const existing=await readProperties();const ids=new Set(existing.map(p=>p.id));const missing=RECOVERY_PROPERTIES.filter(p=>!ids.has(p.id));if(missing.length)await ensureItems(missing);try{await withBlobAuth(a=>put(RECOVERY_MARKER,JSON.stringify({seededAt:new Date().toISOString(),ids:RECOVERY_PROPERTIES.map(p=>p.id),version:3}),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}))}catch(e){if(!blobAuthError(e))throw e}}
function clean(input:any,existing?:Property):Property{const id=String(input.id||existing?.id||crypto.randomUUID()),status=String(input.status||existing?.status||'Available');const photos=Array.isArray(input.photos)?input.photos:(existing?.photos||[]);return{id,title:String(input.title??existing?.title??'').trim().slice(0,160),propertyType:String(input.propertyType??existing?.propertyType??'').trim().slice(0,80),location:String(input.location??existing?.location??'').trim().slice(0,160),price:String(input.price??existing?.price??'').trim().slice(0,80),minBudget:input.minBudget===''||input.minBudget==null?(existing?.minBudget??null):Number(input.minBudget)||0,maxBudget:input.maxBudget===''||input.maxBudget==null?(existing?.maxBudget??null):Number(input.maxBudget)||0,area:String(input.area??existing?.area??'').trim().slice(0,80),bedrooms:String(input.bedrooms??existing?.bedrooms??'').trim().slice(0,40),status:STATUSES.has(status)?status as Property['status']:'Available',description:String(input.description??existing?.description??'').trim().slice(0,2000),createdAt:existing?.createdAt||new Date().toISOString(),photos:photos.filter((x:any)=>typeof x==='string'&&x.startsWith('https://')).slice(0,12)}}
export default async function handler(req:any,res:any){if(!authorized(req))return send(res,401,{error:'Unauthorized'});try{if(req.method==='GET'){await seed();return send(res,200,{properties:await readProperties()})}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const body=parseBody(req),action=String(body.action||'upsert'),all=await readProperties();const itemBlobs=await withBlobAuth(a=>list({prefix:ITEM_PREFIX,...a}));if(!itemBlobs.blobs?.length&&all.length)await ensureItems(all);
if(action==='uploadPhoto'){const id=String(body.id||''),dataUrl=String(body.dataUrl||''),p=all.find(x=>x.id===id);if(!p)return send(res,404,{error:'Property not found.'});if(!dataUrl.startsWith('data:image/'))return send(res,400,{error:'Please upload an image file.'});if(dataUrl.length>4000000)return send(res,413,{error:'Image is too large. Please choose a smaller photo.');const m=dataUrl.match(/^data:(image\/(?:jpeg|jpg|png|webp));base64,(.+)$/);if(!m)return send(res,400,{error:'Unsupported image format.'});const ext=m[1].includes('png')?'png':m[1].includes('webp')?'webp':'jpg',photoId=`${id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,pathname=`${PHOTO_PREFIX}${encodeURIComponent(photoId)}.${ext}`;const blob=await withBlobAuth(a=>put(pathname,Buffer.from(m[2],'base64'),{access:'public',addRandomSuffix:false,contentType:m[1],...a}));const updated={...p,photos:[...(p.photos||[]),blob.url].slice(-12)};await withBlobAuth(a=>put(itemPath(id),JSON.stringify(updated),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));return send(res,200,{ok:true,property:updated,properties:all.map(x=>x.id===id?updated:x)})}
if(action==='deletePhoto'){const id=String(body.id||''),url=String(body.url||''),p=all.find(x=>x.id===id);if(!p)return send(res,404,{error:'Property not found.'});const updated={...p,photos:(p.photos||[]).filter(x=>x!==url)};await withBlobAuth(a=>put(itemPath(id),JSON.stringify(updated),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));return send(res,200,{ok:true,property:updated,properties:all.map(x=>x.id===id?updated:x)})}
if(action==='delete'){const id=String(body.id||''),next=all.filter(x=>x.id!==id);if(next.length===all.length)return send(res,404,{error:'Property not found'});await withBlobAuth(a=>del(itemPath(id),a));return send(res,200,{ok:true,properties:next})}
const idx=all.findIndex(x=>x.id===String(body.id||'')),property=clean(body,idx>=0?all[idx]:undefined);if(!property.title||!property.propertyType||!property.location)return send(res,400,{error:'Title, property type and location are required.'});await withBlobAuth(a=>put(itemPath(property.id),JSON.stringify(property),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));const next=idx>=0?all.map((x,i)=>i===idx?property:x):[property,...all];return send(res,200,{ok:true,property,properties:next})}catch(e){console.error('properties error',e);return send(res,500,{error:'Unable to access property inventory.'})}}